// Diagnostic rule catalog (MS-VBAL Phase 5: Active Diagnostics).
//
// Every active diagnostic the analyzer can raise is described here once: a
// stable `code` (shown in the Problems panel and usable in `// xlide-disable`
// style tooling later), a human title, a default severity, category, VBE compile
// equivalence, the MS-VBAL section it enforces, and a confidence level. Only
// *high-confidence*, deterministic rules are enabled - rules that would need an
// expression-level binder or a complete host catalogue to avoid false positives
// remain deliberately out of scope until the binder can prove them.
//
// The cross-module call rule that is enabled - `unknownCallStatement` - fires
// only on a *call statement* whose callee is a bare (non-member) identifier (the
// lone-identifier `DoStartup`, the parenless `MsgBox "hi"`, or `Call Foo`) whose
// name resolves to no procedure anywhere in the project, no VBA runtime
// function/statement, no host global or Application member, and no in-scope
// declaration. The `undeclaredVariable` rule follows the same shape: it only
// fires when project-visible identifiers are available, and it scans
// high-confidence write/read positions while skipping type-name, label,
// named-argument, and unresolved external-call positions.
//
// Pure data: no `vscode` dependency. The VS Code layer maps `severity` onto
// `vscode.DiagnosticSeverity` and `code`/`source` onto the diagnostic.

/** Severity of a diagnostic, independent of the VS Code enum. */
export type DiagnosticSeverity = 'error' | 'warning' | 'information';

/** User-configurable severity override value for an analysis rule. */
export type DiagnosticSeverityOverride = DiagnosticSeverity | 'off';

/** Analysis suppression scopes exposed by the project analysis UI. */
export type DiagnosticSuppressionScope = 'block' | 'member' | 'module';

const DEFAULT_DIAGNOSTIC_SUPPRESSION_SCOPES: readonly DiagnosticSuppressionScope[] = [
	'block',
	'member',
	'module',
];

/** Broad purpose bucket used by tests, docs, and future filtering. */
export type DiagnosticCategory =
	| 'syntax'
	| 'lexer'
	| 'parser'
	| 'realtime-recovery'
	| 'declaration'
	| 'semantic'
	| 'project-symbol'
	| 'module-kind'
	| 'office-host'
	| 'style';

/** Why a rule is surfaced at its default severity. */
export type DiagnosticEvidenceKind =
	| 'compile-error'
	| 'deterministic-runtime-error'
	| 'runtime-risk'
	| 'style-policy';

/** Static description of a single diagnostic rule. */
export interface DiagnosticRuleMetadata {
	/** Stable identifier shown as the diagnostic code. */
	code: string;
	/** Short human-readable title. */
	title: string;
	/** Severity used unless the user overrides it. */
	defaultSeverity: DiagnosticSeverity;
	/** Broad purpose bucket for the diagnostic. */
	category: DiagnosticCategory;
	/** True when the diagnostic is expected to match a VBE compile failure. */
	vbeCompileEquivalent: boolean;
	/** Distinguishes compile-time errors from deterministic runtime errors. */
	diagnosticKind: DiagnosticEvidenceKind;
	/** Always 'XLIDE' - the diagnostic source label. */
	source: 'XLIDE';
	/** MS-VBAL section (or other authority) the rule enforces. */
	specReference?: string;
	/** True when the rule needs the whole project, not a single module. */
	requiresWholeProject?: boolean;
	/** Suppression scopes that make sense for this diagnostic rule before source-position filtering. */
	suppressionScopes?: readonly DiagnosticSuppressionScope[];
	/** True when an error rule is allowed to be downgraded to warning by user settings. */
	allowSeverityDowngrade?: boolean;
	/**
	 * `unnecessary` marks code the module does not need: the editor fades
	 * the range instead of underlining it, the way it does for an unused
	 * import elsewhere.
	 */
	tag?: 'unnecessary';
	/** How certain the rule is that a flagged construct is genuinely wrong. */
	confidence: 'high' | 'medium' | 'low';
}

/** The catalogue of active diagnostic rules, keyed by a stable rule name. */
export const DIAGNOSTIC_RULES = {
	unterminatedString: {
		code: 'unterminated-string',
		title: 'Unterminated string literal',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.4',
		confidence: 'high',
	},
	invalidLineContinuation: {
		code: 'invalid-line-continuation',
		title: 'Invalid line continuation',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.2.2',
		confidence: 'high',
	},
	duplicateProcedure: {
		code: 'duplicate-procedure',
		title: 'Ambiguous (duplicate) procedure name in module',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3',
		confidence: 'high',
	},
	duplicateDeclaration: {
		code: 'duplicate-declaration',
		title: 'Duplicate declaration in the current scope',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2 / 5.3',
		confidence: 'high',
	},
	duplicateModuleMember: {
		code: 'duplicate-module-variable',
		title: 'Duplicate module-level declaration',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3',
		confidence: 'high',
	},
	duplicateEnumMember: {
		code: 'duplicate-enum-member',
		title: 'Duplicate Enum member',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.4',
		confidence: 'high',
	},
	duplicateTypeField: {
		code: 'duplicate-type-field',
		title: 'Duplicate Type field',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.3',
		confidence: 'high',
	},
	ambiguousProjectProcedure: {
		code: 'ambiguous-project-procedure',
		title: 'Ambiguous unqualified call to a name two modules export',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE oracle: Ambiguous name detected',
		confidence: 'high',
	},
	ambiguousEnumMember: {
		code: 'ambiguous-enum-member',
		title: 'Ambiguous Enum member reference',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE oracle: Ambiguous name detected',
		confidence: 'high',
	},
	declareMissingPtrSafe: {
		code: 'declare-missing-ptrsafe',
		title: 'Declare statement missing PtrSafe for 64-bit Office',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBA 7 Declare statement PtrSafe requirement for 64-bit Office',
		confidence: 'high',
	},
	constAssignment: {
		code: 'const-assignment',
		title: 'Assignment to a constant',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.3.1',
		confidence: 'high',
	},
	optionExplicitMissing: {
		code: 'option-explicit-missing',
		title: 'Option Explicit is not specified',
		defaultSeverity: 'warning',
		category: 'style',
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.4.1.1',
		suppressionScopes: ['module'],
		confidence: 'high',
	},
	undeclaredVariable: {
		code: 'undeclared-variable',
		title: 'Variable not defined',
		defaultSeverity: 'error',
		category: 'project-symbol',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.4.1.1',
		requiresWholeProject: true,
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	unusableDeclare: {
		code: 'unusable-declare',
		title: 'Declare that fails on every call',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime errors 48, 49, 452 and 453 on a Declare whose calling convention, Lib or Alias no call can use (issue #254, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	invalidProcedureHeader: {
		code: 'invalid-proc-header',
		title: 'Invalid procedure declaration',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1',
		confidence: 'high',
	},
	invalidIdentifierStart: {
		code: 'invalid-identifier-start',
		title: 'Invalid identifier start',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.5',
		confidence: 'high',
	},
	invalidIdentifierCharacter: {
		code: 'invalid-identifier-character',
		title: 'Invalid character in identifier',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.5 (identifier) / VBE oracle',
		confidence: 'high',
	},
	moduleDeclarationInProcedure: {
		code: 'module-declaration-in-procedure',
		title: 'Module-level declaration inside procedure',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2 / 5.3',
		confidence: 'high',
	},
	moduleDeclarationAfterProcedure: {
		code: 'module-declaration-after-procedure',
		title: 'Module-level declaration after procedure',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2 / 5.3',
		confidence: 'high',
	},
	statementOutsideProcedure: {
		code: 'statement-outside-procedure',
		title: 'Statement outside procedure',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2 / 5.4',
		confidence: 'high',
	},
	invalidDeclarationName: {
		code: 'invalid-declaration-name',
		title: 'Reserved keyword used as a declaration name',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.5.2',
		confidence: 'high',
	},
	unbalancedParens: {
		code: 'unbalanced-parens',
		title: 'Unbalanced parentheses',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.1',
		confidence: 'high',
	},
	argumentCount: {
		code: 'argument-count',
		title: 'Wrong number of arguments',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.1',
		confidence: 'high',
	},
	argumentTypeMismatch: {
		code: 'argument-type-mismatch',
		title: 'Argument type mismatch',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1 / runtime type coercion and numeric overflow',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	argumentObjectTypeMismatch: {
		code: 'argument-object-type-mismatch',
		title: 'Object argument type mismatch',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1',
		confidence: 'high',
	},
	byRefArgumentTypeMismatch: {
		code: 'byref-argument-type-mismatch',
		title: 'ByRef argument type mismatch',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1 / VBE oracle: ByRef argument type mismatch',
		confidence: 'high',
	},
	assignmentTypeMismatch: {
		code: 'assignment-type-mismatch',
		title: 'Assignment type mismatch',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.3 / runtime type coercion and numeric overflow',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	arrayAssignmentToScalar: {
		code: 'array-assignment-to-scalar',
		title: 'Array cannot be assigned to scalar',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.3 / VBE oracle: Type mismatch',
		confidence: 'high',
	},
	arrayTargetAssignment: {
		code: 'array-target-assignment',
		title: "Can't assign to array",
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: "VBE \"Can't assign to array\": a fixed-size array, a scalar into a dynamic array, or an array of another element type (issue #194, Excel 16.0)",
		confidence: 'high',
	},
	arrayBoundRequiresArray: {
		code: 'array-bound-requires-array',
		title: 'Array bound function requires array',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL LBound/UBound / VBE oracle: Expected array',
		confidence: 'high',
	},
	scalarIndexed: {
		code: 'scalar-indexed',
		title: 'A value that is no array, indexed',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Expected array" on a number, string or user-defined type local or Type field given a subscript (issue #417, Excel 16.0)',
		confidence: 'high',
	},
	missingReturnAssignment: {
		code: 'missing-return-assignment',
		title: 'Function has no return assignment',
		defaultSeverity: 'warning',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'runtime-risk',
		source: 'XLIDE',
		specReference: 'VBA Function return variable semantics',
		confidence: 'high',
	},
	assignmentObjectTypeMismatch: {
		code: 'assignment-object-type-mismatch',
		title: 'Object assignment type mismatch',
		defaultSeverity: 'error',
		category: 'semantic',
		// A Set of the wrong class compiles and raises 13 when it runs (issue #202).
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.3 / Set statement; VBE runtime error 13: Type mismatch',
		confidence: 'high',
	},
	readonlyMemberAssignment: {
		code: 'readonly-member-assignment',
		title: 'Assignment to a read-only member',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: "VBE oracle: Can't assign to read-only property; Wrong number of arguments or invalid property assignment; Assignment to constant not permitted",
		confidence: 'high',
	},
	setRequired: {
		code: 'set-required',
		title: 'Object assignment requires Set',
		defaultSeverity: 'error',
		category: 'semantic',
		// A bare assignment to an object target compiles cleanly and fails at
		// runtime with error 91, not at compile time (VBE-oracle verified across
		// `= Null`, `= New`, and Function-return-name assignment). It shares the
		// runtime-91 class with `object-variable-not-set`.
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 91: Object variable or With block variable not set (MS-VBAL 5.4.3 / Set statement)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	typeOfIsAlwaysFalse: {
		code: 'typeof-is-always-false',
		title: "'TypeOf ... Is' is always False",
		defaultSeverity: 'warning',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'runtime-risk',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.6 (TypeOf...Is expression)',
		confidence: 'high',
	},
	isOperatorNonObject: {
		code: 'is-operator-non-object',
		title: "'Is' operator requires object operands",
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.6 (Is operator)',
		confidence: 'high',
	},
	nonScalarBinaryOperand: {
		code: 'non-scalar-binary-operand',
		title: 'Operator requires a scalar operand',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.6 (binary operators) / VBE oracle: array operand Type mismatch',
		confidence: 'high',
	},
	argumentShapeMismatch: {
		code: 'argument-shape-mismatch',
		title: 'Argument shape (array/Type vs scalar) mismatch',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference:
			'MS-VBAL 5.3.1 (argument passing) / VBE oracle: ByRef argument type mismatch; array or user-defined type expected',
		confidence: 'high',
	},
	parameterDefaultNotConstant: {
		code: 'parameter-default-not-constant',
		title: 'Optional default must be a constant expression',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.5 (Optional default-value is a constant-expression)',
		confidence: 'high',
	},
	constValueNotConstant: {
		code: 'const-value-not-constant',
		title: 'Const value must be a constant expression',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.4 (Const declaration value is a constant-expression)',
		confidence: 'high',
	},
	enumMemberNotConstant: {
		code: 'enum-member-not-constant',
		title: 'Enum member value must be a constant expression',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.4 (Enum member value is a constant-expression)',
		confidence: 'high',
	},
	declarationForwardReference: {
		code: 'declaration-forward-reference',
		title: 'Declaration refers to one further down the module',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.2 constant declarations; VBE "Constant expression required" and "Forward reference to user-defined type" (issue #211, Excel 16.0)',
		confidence: 'high',
	},
	circularDeclarationDependency: {
		code: 'circular-declaration-dependency',
		title: 'Declaration depends on itself through a cycle',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Circular dependencies between modules" (issue #211, Excel 16.0)',
		confidence: 'high',
	},
	enumMemberTypeMismatch: {
		code: 'enum-member-type-mismatch',
		title: 'Enum member value is a string',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.4 (Enum member values are Long); VBE "Type mismatch" (issue #210, Excel 16.0)',
		confidence: 'high',
	},
	invalidLineNumber: {
		code: 'invalid-line-number',
		title: 'Line number the VBE refuses',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.1.1 line numbers: 0 to 2147483647, at the start of a line; VBE "Syntax error" (issues #210 and #230, Excel 16.0)',
		confidence: 'high',
	},
	missingLibraryReference: {
		code: 'missing-library-reference',
		title: 'Type library not referenced',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE oracle: User-defined type not defined',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	memberNotFound: {
		code: 'member-not-found',
		title: 'Object member not found',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE oracle: Method or data member not found',
		requiresWholeProject: true,
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	fileNumberZero: {
		code: 'file-number-zero',
		title: 'File number outside 1 to 512',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 52: Bad file name or number (issues #123 and #262, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	invalidPropertyUse: {
		code: 'invalid-property-use',
		title: 'Invalid use of property',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Invalid use of property" (issue #266, Excel 16.0)',
		confidence: 'high',
	},
	fileReadPastEnd: {
		code: 'file-read-past-end',
		title: 'Reading a file the procedure created empty',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 62: Input past end of file (issue #262, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	emptyFilePath: {
		code: 'empty-file-path',
		title: 'Empty file path',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime errors 53, 75 and 76 on an empty path (issue #262, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	fileUsedAfterClose: {
		code: 'file-used-after-close',
		title: 'File statement on a closed file number',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 52: Bad file name or number (issue #123, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	fileModeMismatch: {
		code: 'file-mode-mismatch',
		title: 'File statement the open mode forbids',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 54: Bad file mode (issue #123, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	fileAlreadyOpen: {
		code: 'file-already-open',
		title: 'File number opened twice',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 55: File already open (issue #123, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	arithmeticOverflow: {
		code: 'arithmetic-overflow',
		title: 'Arithmetic overflow',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.6.9.3 operator result types; VBE runtime error 6: Overflow (issue #116, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	constOverflow: {
		code: 'const-overflow',
		title: 'Const value overflows',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.6.9.3; VBE compile error: Overflow (issue #116, Excel 16.0)',
		confidence: 'high',
	},
	constEvaluationError: {
		code: 'const-evaluation-error',
		title: 'Const value that does not evaluate',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.1 constant expressions; VBE compile errors Division by zero and Type mismatch (issue #235, Excel 16.0)',
		confidence: 'high',
	},
	forCounterOverflow: {
		code: 'for-counter-overflow',
		title: 'For counter overflows after its last pass',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.3; VBE runtime error 6: Overflow (issue #116, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	strayCharacter: {
		code: 'stray-character',
		title: 'Character VBA does not use',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.1 special-token; VBE "Syntax error" on ; ` { } @ ~ | and a non-breaking space (issue #132, Excel 16.0)',
		confidence: 'high',
	},
	lineTooLong: {
		code: 'line-too-long',
		title: 'Physical line over 1023 characters',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE line limit: 1023 characters compile, 1024 are refused (issue #133, Excel 16.0)',
		confidence: 'high',
	},
	dateLiteralInvalid: {
		code: 'date-literal-invalid',
		title: 'Date literal the VBE refuses',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.3 date tokens; VBE "Syntax error" (issue #133, Excel 16.0)',
		confidence: 'high',
	},
	duplicateConstDirective: {
		code: 'duplicate-const-directive',
		title: 'Duplicate #Const',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.4.1 #Const; VBE "Duplicate definition" (issue #130, Excel 16.0)',
		confidence: 'high',
	},
	nullDirectiveCondition: {
		code: 'null-directive-condition',
		title: '#If condition is Null',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.4 conditional compilation; VBE "Invalid use of Null" (issue #208, Excel 16.0)',
		confidence: 'high',
	},
	directiveTrailingStatement: {
		code: 'directive-trailing-statement',
		title: 'Code after a compiler directive on its line',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.4 conditional compilation; VBE "An # ElseIf, # Else, or # EndIf must be preceded by an # If clause" (issue #130, Excel 16.0)',
		confidence: 'high',
	},
	arrayParameterForm: {
		code: 'array-parameter-form',
		title: 'Array parameter cannot be ByVal or Optional',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.5; VBE "Array argument must be ByRef" / "Optional argument must be Variant or intrinsic type with a default value" (issue #124, Excel 16.0)',
		confidence: 'high',
	},
	duplicateDeftype: {
		code: 'duplicate-deftype',
		title: 'Duplicate Deftype statement',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.1.3; VBE "Duplicate Deftype statement" (issue #124, Excel 16.0)',
		confidence: 'high',
	},
	bracketedVariableName: {
		code: 'bracketed-variable-name',
		title: 'Bracketed name in a variable declaration',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.5.3 foreign-name; VBE "Syntax error" on Dim [name] (issue #124, Excel 16.0)',
		confidence: 'high',
	},
	implementsMemberMissing: {
		code: 'implements-member-missing',
		title: 'Interface member not implemented',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.4.1; VBE "Object module needs to implement ... for interface ..." (issue #125, Excel 16.0)',
		confidence: 'high',
	},
	implementsMemberSignature: {
		code: 'implements-member-signature',
		title: 'Interface member implemented with another signature',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.4.1; VBE "Procedure declaration does not match description of event or procedure having the same name" (issue #125, Excel 16.0)',
		confidence: 'high',
	},
	eventHandlerSignature: {
		code: 'event-handler-signature',
		title: 'Event handler declared unlike its event',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Procedure declaration does not match description of event or procedure having the same name"; events from the Office and MSForms type libraries (issue #195, Excel 16.0)',
		confidence: 'high',
	},
	collectionOperand: {
		code: 'collection-operand',
		title: 'Collection or object without a value used as an operand',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Argument not optional" on a Collection whose default member Item takes an index (issue #125, Excel 16.0); "Type mismatch" on a Word Paragraph, whose default member Range holds an object (issue #462, Word 16.0)',
		confidence: 'high',
	},
	subUsedAsValue: {
		code: 'sub-used-as-value',
		title: 'Sub used as a value',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Expected Function or variable" (issue #125, Excel 16.0)',
		confidence: 'high',
	},
	remAfterThen: {
		code: 'rem-after-then',
		title: 'Rem after Then',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.1 comment / 5.4.2.9 single-line If; VBE "Syntax error" (issue #125, Excel 16.0)',
		confidence: 'high',
	},
	malformedStatement: {
		code: 'malformed-statement',
		title: 'Line the VBE cannot parse',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE compile errors on unfinished lines: an unknown #directive, an unclosed [bracket, Sub with no name, a word after a parameter, an Enum line that is no member (issue #234, Excel 16.0)',
		confidence: 'high',
	},
	reservedKeywordInExpression: {
		code: 'reserved-keyword-in-expression',
		title: 'Statement keyword where a value goes',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.5.2 reserved identifiers; VBE "Syntax error", or "Expected: expression" in a Const (issue #234, Excel 16.0)',
		confidence: 'high',
	},
	remAfterStatement: {
		code: 'rem-after-statement',
		title: 'Rem after a statement',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.1 comment / 5.4.2.9 single-line If; VBE "Syntax error", or "Expected: end of statement" at module level (issue #231, Excel 16.0)',
		confidence: 'high',
	},
	floatLiteralOverflow: {
		code: 'float-literal-overflow',
		title: 'Floating-point literal overflows',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.2 FLOAT; VBE "Syntax error" on 1E400 (issue #125, Excel 16.0)',
		confidence: 'high',
	},
	hostArgumentOutOfRange: {
		code: 'host-argument-out-of-range',
		title: 'Host argument out of range',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'Office object model: 1-based collections, cell rows and columns from 1 (issue #122, Excel/Word/PowerPoint 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	hostPropertyValueOutOfRange: {
		code: 'host-property-value-out-of-range',
		title: 'Host property value out of range',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'Office object model: property ranges the host refuses, measured in Excel/Word/PowerPoint 16.0 (issue #204)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	sheetNameInvalid: {
		code: 'sheet-name-invalid',
		title: 'Sheet name Excel refuses',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'Excel runtime error 1004: invalid name for a sheet or chart (issue #122, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	sheetNotInWorkbook: {
		code: 'sheet-not-in-workbook',
		title: 'Sheet the workbook does not have',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'Excel runtime error 9: Subscript out of range from ThisWorkbook.Sheets, Worksheets or Charts given a name or index the workbook lacks (issue #229, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	pasteWithNothingCopied: {
		code: 'paste-with-nothing-copied',
		title: 'PasteSpecial after the clipboard was emptied',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'Excel runtime error 1004: PasteSpecial method of Range class failed, after Application.CutCopyMode = False with no Copy or Cut since (issue #308, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	multiCellRangeAsScalar: {
		code: 'multi-cell-range-as-scalar',
		title: 'Multi-cell range read as a scalar',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 13: Type mismatch on a Range value that is an array (issue #122, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	collectionIndexOutOfRange: {
		code: 'collection-index-out-of-range',
		title: 'Collection index out of range',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime errors 5 and 9 on VBA.Collection (issue #121, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	collectionKeyNotFound: {
		code: 'collection-key-not-found',
		title: 'Collection key not found',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 5 on VBA.Collection (issue #121, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	collectionKeyInUse: {
		code: 'collection-key-in-use',
		title: 'Collection key already in use',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 457 on VBA.Collection (issue #121, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	collectionAddArgument: {
		code: 'collection-add-argument',
		title: 'Collection Add argument refused',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime errors 13 and 5 from VBA.Collection.Add: a key that is not a string, Before with After (issue #219, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	variantValueMisuse: {
		code: 'variant-value-misuse',
		title: 'Variant value used as another kind',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime errors 424 and 13 on a Variant holding a scalar or an array (issue #121, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	objectDefaultValue: {
		code: 'object-default-value',
		title: 'Object read as a value has no default member',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime errors 438 and 450 reading an object with no default member, or one that needs an argument (issue #183, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	runtimeMemberNotFound: {
		code: 'runtime-member-not-found',
		title: 'Member not found at run time',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: "VBE runtime error 438: Object doesn't support this property or method (issue #121, Excel 16.0)",
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	fileRecordZero: {
		code: 'file-record-zero',
		title: 'Record number 0',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 63: Bad record number (issue #123, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	handlerFallThrough: {
		code: 'handler-fall-through',
		title: 'Execution falls into an error handler that re-raises',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: "VBE runtime error 5 from Err.Raise Err.Number with Err.Number 0 (issue #117, Excel 16.0)",
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	resumeWithoutError: {
		code: 'resume-without-error',
		title: 'Resume with no error handler installed',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 20: Resume without error (issue #117, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	returnWithoutGosub: {
		code: 'return-without-gosub',
		title: 'Execution falls into a GoSub target',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 3: Return without GoSub (issue #117, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	recursivePropertyAccessor: {
		code: 'recursive-property-accessor',
		title: 'Property procedure calls itself',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 28: Out of stack space (issue #117, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	unboundedRecursion: {
		code: 'unbounded-recursion',
		title: 'Sub or Function calls itself on every run',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 28: Out of stack space (issue #240, Excel 16.0)',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	objectVariableNotSet: {
		code: 'object-variable-not-set',
		title: 'Object variable not set',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: "VBE runtime error 91: Object variable or With block variable not set",
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	lateBoundFriendMember: {
		code: 'late-bound-friend-member',
		title: 'Friend member reached through a late-bound receiver',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 438: Object does not support this property or method',
		requiresWholeProject: true,
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	stringArithmeticCoercion: {
		code: 'string-arithmetic-coercion',
		title: 'Nonnumeric string in numeric expression',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.6 / runtime type coercion',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	divisionByZero: {
		code: 'division-by-zero',
		title: 'Division by zero',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.6 / runtime division by zero',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	runtimeArgumentValue: {
		code: 'runtime-argument-value',
		title: 'Invalid runtime argument value',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.6 / VBA runtime argument bounds and VBE oracle runtime error 5',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	runtimeConversionValue: {
		code: 'runtime-conversion-value',
		title: 'Invalid runtime conversion value',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.6 / VBA runtime conversion and VBE oracle runtime error 13',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	unknownCallStatement: {
		code: 'unknown-call',
		title: 'Sub or Function not defined',
		defaultSeverity: 'error',
		category: 'project-symbol',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.1',
		requiresWholeProject: true,
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	nonCallableCallStatement: {
		code: 'non-callable-call',
		title: 'Identifier is not callable',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.1',
		confidence: 'high',
	},
	dimInitializer: {
		code: 'dim-initializer',
		title: 'Declaration cannot include an initializer (VB.NET syntax)',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.1',
		confidence: 'high',
	},
	fixedArrayRedim: {
		code: 'fixed-array-redim',
		title: 'Fixed-size array cannot be ReDimmed',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL ReDim statement',
		confidence: 'high',
	},
	scalarRedim: {
		code: 'scalar-redim',
		title: 'Scalar variable cannot be ReDimmed',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL ReDim statement / VBE oracle: Expected array',
		confidence: 'high',
	},
	redimPreserveDimensionChange: {
		code: 'redim-preserve-dimension-change',
		title: 'ReDim Preserve can only resize the last dimension',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL ReDim Preserve statement',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	redimImpossibleBounds: {
		code: 'redim-impossible-bounds',
		title: 'ReDim lower bound is greater than upper bound',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL ReDim statement / VBE oracle runtime error 9',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	arrayDeclarationImpossibleBounds: {
		code: 'array-declaration-impossible-bounds',
		title: 'Array declaration lower bound is greater than upper bound',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.1 (array declaration bounds)',
		confidence: 'high',
	},
	arrayTemporarilyLocked: {
		code: 'array-temporarily-locked',
		title: 'Array is locked while it is resized or erased',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 10: This array is fixed or temporarily locked',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	objectUsedAfterDelete: {
		code: 'object-used-after-delete',
		title: 'Object used after it is deleted or closed',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'Excel object model: a deleted sheet, shape or name, a closed workbook or an unlisted table raises 424, 1004 or -2147221080',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	longLongNarrowing: {
		code: 'longlong-narrowing',
		title: 'LongLong narrowed implicitly in 64-bit VBA',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBA 64-bit: a LongLong or LongPtr converts to no narrower whole-number type implicitly; VBE compile error Type mismatch',
		confidence: 'high',
	},
	addressOfMisuse: {
		code: 'addressof-misuse',
		title: 'AddressOf where the VBE refuses it',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.6.16.8 (AddressOf expressions) / VBE compile errors',
		confidence: 'high',
	},
	unallocatedDynamicArrayAccess: {
		code: 'unallocated-dynamic-array-access',
		title: 'Dynamic array is not allocated',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: "VBE runtime error 9: Subscript out of range; 92 for For Each",
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	arraySubscriptOutOfBounds: {
		code: 'array-subscript-out-of-bounds',
		title: 'Array subscript out of range',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: false,
		diagnosticKind: 'deterministic-runtime-error',
		source: 'XLIDE',
		specReference: 'VBE runtime error 9: Subscript out of range',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
	midStatementLiteralTarget: {
		code: 'mid-statement-literal-target',
		title: 'Mid statement target must be a writable String variable',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.3.4 (Mid/MidB statement)',
		confidence: 'high',
	},
	invalidEraseTarget: {
		code: 'invalid-erase-target',
		title: 'Erase target must be a variable or array name',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL Erase statement',
		confidence: 'high',
	},
	eraseRequiresArray: {
		code: 'erase-requires-array',
		title: 'Erase target must be array or Variant',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL Erase statement / VBE oracle: Expected array',
		confidence: 'high',
	},
	typeDeclarationCharacterAsClause: {
		code: 'type-declaration-character-as-clause',
		title: 'Invalid type-declaration character with As',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.1 / 5.3.1 type-declaration characters',
		confidence: 'high',
	},
	unexpectedDeclarationToken: {
		code: 'unexpected-declaration-token',
		title: 'Unexpected token after declaration type',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.1 / VBE oracle: Syntax error',
		confidence: 'high',
	},
	fixedLengthStringSize: {
		code: 'fixed-length-string-size',
		title: 'Invalid fixed-length String size',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL fixed-length String bounds / VBE oracle: Invalid length for fixed-length string',
		confidence: 'high',
	},
	objectModulePublicMember: {
		code: 'object-module-public-member',
		title: 'Invalid public member in object module',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE oracle: public object-module member restrictions',
		confidence: 'high',
	},
	eventDeclarationModuleKind: {
		code: 'event-declaration-module-kind',
		title: 'Event declaration is not valid in this module',
		defaultSeverity: 'error',
		category: 'module-kind',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.5: Event declarations belong to object modules',
		confidence: 'high',
	},
	withEventsDeclaration: {
		code: 'withevents-declaration',
		title: 'Invalid WithEvents declaration',
		defaultSeverity: 'error',
		category: 'module-kind',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3: WithEvents object variable declarations',
		confidence: 'high',
	},
	friendDeclaration: {
		code: 'friend-declaration',
		title: 'Invalid Friend declaration',
		defaultSeverity: 'error',
		category: 'module-kind',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL Friend procedure visibility: object-module procedures only',
		confidence: 'high',
	},
	implementsStatementPlacement: {
		code: 'implements-statement-placement',
		title: 'Invalid Implements statement',
		defaultSeverity: 'error',
		category: 'module-kind',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL Implements statement: module-level object-module declaration',
		confidence: 'high',
	},
	raiseEventUndeclaredEvent: {
		code: 'raiseevent-undeclared-event',
		title: 'RaiseEvent target is not declared',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL RaiseEvent statement: event name resolution',
		confidence: 'high',
	},
	eventHandlerWrongModule: {
		code: 'event-handler-module-scope',
		title: 'Event handler is not wired in this module',
		defaultSeverity: 'information',
		category: 'module-kind',
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'Office document-module event binding',
		confidence: 'high',
	},
	invalidAsTypeName: {
		code: 'invalid-as-type-name',
		title: 'Invalid type name',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.5.2 / 5.2.3.1',
		confidence: 'high',
	},
	invalidNewTypeName: {
		code: 'invalid-new-type-name',
		title: 'Type cannot be created with New',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.1 / 5.6.9',
		confidence: 'high',
	},
	setRequiresObject: {
		code: 'set-requires-object',
		title: 'Set assignment requires an object variable',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.3',
		confidence: 'high',
	},
	scalarMemberAccess: {
		code: 'scalar-member-access',
		title: 'Member access on scalar variable',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE oracle: Invalid qualifier / Syntax error',
		confidence: 'high',
	},
	callRequiresParens: {
		code: 'call-requires-parens',
		title: 'Call statement requires parentheses around arguments',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.1',
		confidence: 'high',
	},
	invalidExplicitCallTarget: {
		code: 'invalid-explicit-call-target',
		title: 'Invalid explicit Call target',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE oracle: Syntax error',
		confidence: 'high',
	},
	callStatementForbidsParens: {
		code: 'call-statement-forbids-parens',
		title: 'Standalone zero-argument call cannot use empty parentheses',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.1',
		confidence: 'high',
	},
	expressionCallRequiresParens: {
		code: 'expression-call-requires-parens',
		title: 'Function call in an expression requires parentheses around arguments',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.6.9',
		confidence: 'high',
	},
	callStatementMultiArgParens: {
		code: 'call-statement-multi-arg-parens',
		title: 'Standalone call cannot parenthesize multiple arguments',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.1',
		confidence: 'high',
	},
	invalidExpressionSyntax: {
		code: 'invalid-expression-syntax',
		title: 'Invalid expression syntax',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.6 / VBE oracle: Syntax error',
		confidence: 'high',
	},
	requiredParamAfterOptional: {
		code: 'required-param-after-optional',
		title: 'A required parameter cannot follow an Optional parameter',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.5',
		confidence: 'high',
	},
	parameterArrayAsTypeSyntax: {
		code: 'parameter-array-as-type-syntax',
		title: 'Array parameter parentheses must follow the parameter name',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.5',
		confidence: 'high',
	},
	paramArrayNotLast: {
		code: 'paramarray-not-last',
		title: 'ParamArray must be the final parameter',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.6',
		confidence: 'high',
	},
	paramArrayWithOptional: {
		code: 'paramarray-with-optional',
		title: 'ParamArray cannot be combined with Optional parameters',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.5 / 5.3.1.6',
		confidence: 'high',
	},
	paramArrayNonVariant: {
		code: 'paramarray-non-variant',
		title: 'ParamArray elements must be Variant',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.6',
		confidence: 'high',
	},
	propertySetterMissingValue: {
		code: 'property-setter-missing-value',
		title: 'Property setter is missing value parameter',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.4',
		confidence: 'high',
	},
	propertySetScalarValue: {
		code: 'property-set-scalar-value',
		title: 'Property Set value parameter must be object reference',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.4',
		confidence: 'high',
	},
	propertyLetObjectValue: {
		code: 'property-let-object-value',
		title: 'Property Let value parameter must not be object reference',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.4',
		confidence: 'high',
	},
	propertySetterReturnType: {
		code: 'property-setter-return-type',
		title: 'Property setter cannot declare a return type',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.4',
		confidence: 'high',
	},
	propertyAccessorSignatureMismatch: {
		code: 'property-accessor-signature-mismatch',
		title: 'Property accessors have incompatible signatures',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.4',
		confidence: 'high',
	},
	parameterDefaultTypeMismatch: {
		code: 'parameter-default-type-mismatch',
		title: 'Parameter default type mismatch',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1 / VBE oracle: Type mismatch',
		confidence: 'high',
	},
	exitWrongProcedure: {
		code: 'exit-wrong-proc',
		title: 'Exit statement does not match the enclosing procedure',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.1.3',
		confidence: 'high',
	},
	undefinedLabel: {
		code: 'undefined-label',
		title: 'Label not defined',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.1 / VBE oracle: Label not defined',
		confidence: 'high',
	},
	duplicateLabel: {
		code: 'duplicate-label',
		title: 'Duplicate procedure label',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.1',
		confidence: 'high',
	},
	optionAfterDeclaration: {
		code: 'option-after-declaration',
		title: 'Option statement after a procedure',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.1',
		confidence: 'high',
	},
	ifMissingThen: {
		code: 'if-missing-then',
		title: 'If statement is missing Then',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.1',
		confidence: 'high',
	},
	ifReservedKeywordInCondition: {
		code: 'if-reserved-keyword-in-condition',
		title: 'Reserved keyword in If condition',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.1 (If block) / 3.3.5.2 (reserved identifiers) / VBE oracle: Syntax error',
		confidence: 'high',
	},
	caseOutsideSelect: {
		code: 'case-outside-select',
		title: 'Case statement outside Select Case',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.4',
		confidence: 'high',
	},
	duplicateCaseElse: {
		code: 'duplicate-case-else',
		title: 'Duplicate Case Else in Select Case',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.10 (Select Case)',
		confidence: 'high',
	},
	elseWithoutIf: {
		code: 'else-without-if',
		title: "'Else'/'ElseIf' outside an If block",
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.1 (If block) / VBE oracle',
		confidence: 'high',
	},
	invalidAssignmentTarget: {
		code: 'invalid-assignment-target',
		title: 'Cannot assign to a literal value',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.3 (assignment) / VBE oracle',
		confidence: 'high',
	},
	openMissingForMode: {
		code: 'open-missing-for',
		title: "'Open' statement mode without 'For', or no 'As' clause",
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.5.1 (Open statement) / VBE oracle',
		confidence: 'high',
	},
	typeofMissingOperand: {
		code: 'typeof-missing-operand',
		title: "'TypeOf' requires an object expression",
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.6 (TypeOf...Is) / VBE oracle',
		confidence: 'high',
	},
	suffixedLiteralOverflow: {
		code: 'suffixed-literal-overflow',
		title: 'Type-suffixed literal out of range',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.2 (number tokens / type suffixes) / VBE oracle',
		confidence: 'high',
	},
	raiseEventArgumentCount: {
		code: 'raiseevent-argument-count',
		title: 'RaiseEvent passes the wrong number of arguments',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Wrong number of arguments or invalid property assignment" and "Argument not optional" (issue #213, Excel 16.0)',
		confidence: 'high',
	},
	assignmentToProcedureName: {
		code: 'assignment-to-procedure-name',
		title: 'Assignment to a Sub or typed Function from outside it',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Expected Function or variable" and "Function call on left-hand side of assignment must return Variant or Object" (issue #213, Excel 16.0)',
		confidence: 'high',
	},
	forVariableInUse: {
		code: 'for-variable-in-use',
		title: 'For control variable already in use',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.3; VBE "For control variable already in use" (issue #213, Excel 16.0)',
		confidence: 'high',
	},
	forCounterType: {
		code: 'for-counter-type',
		title: 'For counter of a type that cannot count',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.3; VBE "Type mismatch" (issue #213, Excel 16.0)',
		confidence: 'high',
	},
	statementBeforeFirstCase: {
		code: 'statement-before-first-case',
		title: 'Statement between Select Case and the first Case',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.10; VBE "Statements and labels invalid between Select Case and first Case" (issue #213, Excel 16.0)',
		confidence: 'high',
	},
	returnWithValue: {
		code: 'return-with-value',
		title: 'Return with a value',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.14 Return; VBE "Syntax error" (issue #213, Excel 16.0)',
		confidence: 'high',
	},
	withScalarTarget: {
		code: 'with-scalar-target',
		title: 'With on a scalar',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.21 With; VBE "With object must be user-defined type, Object, or Variant" (issue #213, Excel 16.0)',
		confidence: 'high',
	},
	paramArrayPassingMode: {
		code: 'paramarray-passing-mode',
		title: 'ByVal or ByRef on a ParamArray',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.5 ParamArray; VBE "Expected: identifier" (issue #213, Excel 16.0)',
		confidence: 'high',
	},
	udtValueMismatch: {
		code: 'udt-value-mismatch',
		title: 'User-defined type used as a single value',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Type mismatch" (issue #213, Excel 16.0)',
		confidence: 'high',
	},
	lsetTypeMismatch: {
		code: 'lset-type-mismatch',
		title: 'LSet or RSet that cannot copy into its target',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Type mismatch" on LSet between two user-defined types (issue #253, Excel 16.0); "LSet allowed only on strings and user-defined types" and "RSet allowed only on strings" (issue #451, Excel 16.0)',
		confidence: 'high',
	},
	udtVariantCoercion: {
		code: 'udt-variant-coercion',
		title: 'User-defined type handed to a Variant',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Only user-defined types defined in public object modules can be coerced to or from a variant or passed to late-bound functions" (issue #213, Excel 16.0)',
		confidence: 'high',
	},
	arrayBoundNotConstant: {
		code: 'array-bound-not-constant',
		title: 'Dim bound or String length names a variable',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.1 array bounds; VBE "Constant expression required" (issue #216, Excel 16.0)',
		confidence: 'high',
	},
	variableRequired: {
		code: 'variable-required',
		title: 'Constant where a variable is required',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Variable required - can\'t assign to this expression" (issue #216, Excel 16.0)',
		confidence: 'high',
	},
	typeSuffixMismatch: {
		code: 'type-suffix-mismatch',
		title: 'Type-declaration character does not match the declared type',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.5.2; VBE "Type-declaration character does not match declared data type" (issue #216, Excel 16.0)',
		confidence: 'high',
	},
	namedArgumentNotAllowed: {
		code: 'named-argument-not-allowed',
		title: 'Named argument to a function that takes none',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Syntax error" (issue #216, Excel 16.0)',
		confidence: 'high',
	},
	staticOutsideProcedure: {
		code: 'static-outside-procedure',
		title: 'Static at module level',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.1; VBE "Invalid outside procedure" (issue #216, Excel 16.0)',
		confidence: 'high',
	},
	privateTypeInPublicSignature: {
		code: 'private-type-in-public-signature',
		title: 'Private Enum or Type in a public signature',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Private Enum and user defined types cannot be used as parameters or return types for public procedures, public data members, or fields of public user defined types" (issue #212, Excel 16.0)',
		confidence: 'high',
	},
	optionalPropertyValue: {
		code: 'optional-property-value',
		title: 'Property Let or Set value is Optional',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.7 property parameters; VBE "Syntax error" (issue #212, Excel 16.0)',
		confidence: 'high',
	},
	eventParameterForm: {
		code: 'event-parameter-form',
		title: 'Event parameter is Optional or a ParamArray',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.4.3 event declarations; VBE "Syntax error" (issue #212, Excel 16.0)',
		confidence: 'high',
	},
	constInvalidType: {
		code: 'const-invalid-type',
		title: 'Const declared As a type a constant cannot have',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.2 constant declarations; VBE "Invalid data type for constant" and "Expected: type name" (issue #212, Excel 16.0)',
		confidence: 'high',
	},
	emptyEnum: {
		code: 'empty-enum',
		title: 'Empty Enum',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.4 Enum declarations; VBE "Enum without members not allowed" (issue #212, Excel 16.0)',
		confidence: 'high',
	},
	typeMemberWithoutType: {
		code: 'type-member-without-type',
		title: 'Type member without an As clause',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.3 UDT declarations; VBE "Statement invalid inside Type block" (issue #212, Excel 16.0)',
		confidence: 'high',
	},
	typeEnumNameConflict: {
		code: 'type-enum-name-conflict',
		title: 'Type and Enum share a name',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Ambiguous name detected" (issue #212, Excel 16.0)',
		confidence: 'high',
	},
	redimTypeChange: {
		code: 'redim-type-change',
		title: 'ReDim changes an array\'s element type',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.3.3 ReDim; VBE "Can\'t change data types of array elements" (issue #212, Excel 16.0)',
		confidence: 'high',
	},
	emptyType: {
		code: 'empty-type',
		title: 'User-defined Type has no members',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.3 (UDT declaration)',
		confidence: 'high',
	},
	meOutsideObjectModule: {
		code: 'me-outside-object-module',
		title: "'Me' is only valid in an object module",
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.6.2.2 (Me) / VBE oracle',
		confidence: 'high',
	},
	tooManyParameters: {
		code: 'too-many-parameters',
		title: 'Procedure has more than 60 parameters',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1 (procedure parameters) / VBE oracle',
		confidence: 'high',
	},
	wrongNumberOfDimensions: {
		code: 'wrong-number-of-dimensions',
		title: 'Subscript count differs from the array\'s dimensions',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'VBE "Wrong number of dimensions" (issue #248, Excel 16.0)',
		confidence: 'high',
	},
	tooManyArrayDimensions: {
		code: 'too-many-array-dimensions',
		title: 'Array has more than 60 dimensions',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3.1 (array declaration) / VBE oracle',
		confidence: 'high',
	},
	identifierTooLong: {
		code: 'identifier-too-long',
		title: 'Identifier exceeds 255 characters',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.3.5.1 (identifier length) / VBE oracle',
		confidence: 'high',
	},
	optionalUdtParameter: {
		code: 'optional-udt-parameter',
		title: 'Optional parameter cannot be a user-defined type',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1 (Optional parameter) / VBE oracle',
		confidence: 'high',
	},
	byvalUdtParameter: {
		code: 'byval-udt-parameter',
		title: 'User-defined type parameter cannot be ByVal',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1 (parameter passing) / VBE oracle',
		confidence: 'high',
	},
	invalidOptionStatement: {
		code: 'invalid-option-statement',
		title: 'Malformed Option statement',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.1 (module options) / VBE oracle',
		confidence: 'high',
	},
	duplicateOption: {
		code: 'duplicate-option',
		title: 'Duplicate Option statement',
		defaultSeverity: 'error',
		category: 'declaration',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.1 (module options)',
		confidence: 'high',
	},
	memberAccessOutsideWith: {
		code: 'member-access-outside-with',
		title: 'Leading member access outside With block',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.6',
		confidence: 'high',
	},
	exitOutsideBlock: {
		code: 'exit-outside-block',
		title: 'Loop exit statement outside matching loop',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.1.3',
		confidence: 'high',
	},
	elseBranchOrder: {
		code: 'else-branch-order',
		title: 'Else branch must be final in conditional block',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 3.4 / 5.4.2.1',
		confidence: 'high',
	},
	nextVariableMismatch: {
		code: 'next-variable-mismatch',
		title: 'Next variable does not match active For loop',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.5',
		confidence: 'high',
	},
	forEachControlVariableType: {
		code: 'for-each-control-variable-type',
		title: 'For Each control variable must be Variant or Object',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.5',
		confidence: 'high',
	},
	forEachSourceType: {
		code: 'for-each-source-type',
		title: 'For Each source must be collection or array',
		defaultSeverity: 'error',
		category: 'semantic',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.2.5 / VBE oracle: For Each may only iterate over a collection object or an array',
		confidence: 'high',
	},
	vbaTestDirective: {
		code: 'vba-test-directive',
		title: 'Invalid XLIDE VBA test directive',
		defaultSeverity: 'warning',
		category: 'style',
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'docs/xlide_vba_com_test_runner.md',
		confidence: 'high',
	},
	analysisSuppressionDirective: {
		code: 'analysis-suppression-directive',
		title: 'Invalid XLIDE analysis suppression directive',
		defaultSeverity: 'warning',
		category: 'style',
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'docs/xlide_vba_analysis_suppression_comments.md',
		confidence: 'high',
	},
	unusedVariable: {
		code: 'unused-variable',
		title: 'Variable or constant is never used',
		defaultSeverity: 'information',
		category: 'style',
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.2.3 / 5.4.3.1 (declaration scope) plus XLIDE dead-code policy',
		tag: 'unnecessary',
		confidence: 'high',
	},
	variableNeverRead: {
		code: 'variable-never-read',
		title: 'Variable is assigned but never read',
		defaultSeverity: 'information',
		category: 'style',
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.3 (assignment) plus XLIDE dead-code policy',
		tag: 'unnecessary',
		confidence: 'high',
	},
	unusedProcedure: {
		code: 'unused-procedure',
		title: 'Private procedure is never called',
		defaultSeverity: 'information',
		category: 'style',
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.3.1.1 (Private procedure visibility) plus XLIDE dead-code policy',
		requiresWholeProject: true,
		tag: 'unnecessary',
		confidence: 'high',
	},
	unreachableCode: {
		code: 'unreachable-code',
		title: 'Code is never reached',
		defaultSeverity: 'information',
		category: 'style',
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4.1.3 (Exit), 5.4.1.4 (GoTo), 5.4.4 (Resume) plus XLIDE dead-code policy',
		tag: 'unnecessary',
		confidence: 'high',
	},
	docParamMissing: {
		code: 'doc-param-missing',
		title: 'Doc comment does not describe a parameter',
		defaultSeverity: 'warning',
		category: 'style',
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'user_guides/vba-doc-comments.md',
		confidence: 'high',
	},
	docParamUnknown: {
		code: 'doc-param-unknown',
		title: 'Doc comment describes a parameter the declaration does not have',
		defaultSeverity: 'warning',
		category: 'style',
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'user_guides/vba-doc-comments.md',
		confidence: 'high',
	},
	docReturnsMissing: {
		code: 'doc-returns-missing',
		title: 'Doc comment does not describe the return value',
		defaultSeverity: 'warning',
		category: 'style',
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'user_guides/vba-doc-comments.md',
		confidence: 'high',
	},
	docReturnsUnexpected: {
		code: 'doc-returns-unexpected',
		title: 'Doc comment describes a return value the declaration does not have',
		defaultSeverity: 'warning',
		category: 'style',
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'user_guides/vba-doc-comments.md',
		confidence: 'high',
	},
	docTagDuplicate: {
		code: 'doc-tag-duplicate',
		title: 'Doc comment repeats a tag',
		defaultSeverity: 'warning',
		category: 'style',
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'user_guides/vba-doc-comments.md',
		confidence: 'high',
	},
	docTagUnclosed: {
		code: 'doc-tag-unclosed',
		title: 'Doc comment tag is not closed',
		defaultSeverity: 'warning',
		category: 'style',
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'user_guides/vba-doc-comments.md',
		confidence: 'high',
	},
} satisfies Record<string, DiagnosticRuleMetadata>;

/** Structural diagnostics emitted by the dependency-free block-balance analyzer. */
export const STRUCTURAL_DIAGNOSTIC_RULES = {
	missingBlockCloser: {
		code: 'missing-block-closer',
		title: 'Missing block closer',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4 (block statements) / VBE compile structure',
		confidence: 'high',
	},
	unmatchedBlockCloser: {
		code: 'unmatched-block-closer',
		title: 'Unmatched block closer',
		defaultSeverity: 'error',
		category: 'syntax',
		vbeCompileEquivalent: true,
		diagnosticKind: 'compile-error',
		source: 'XLIDE',
		specReference: 'MS-VBAL 5.4 (block statements) / VBE compile structure',
		confidence: 'high',
	},
	mismatchedEndKeyword: {
		code: 'mismatched-end-keyword',
		title: 'Mismatched procedure End keyword',
		defaultSeverity: 'warning',
		category: 'syntax',
		// VBE accepts End Sub/Function/Property interchangeably as procedure
		// closers (oracle-verified: the mismatch compiles), so this is a style
		// warning rather than a compile error.
		vbeCompileEquivalent: false,
		diagnosticKind: 'style-policy',
		source: 'XLIDE',
		specReference: 'VBE accepts End Sub/Function/Property interchangeably (oracle-verified); MS-VBAL 5.3.1',
		allowSeverityDowngrade: true,
		confidence: 'high',
	},
} satisfies Record<string, DiagnosticRuleMetadata>;

const DIAGNOSTIC_METADATA_BY_CODE = new Map<string, DiagnosticRuleMetadata>(
	[
		...Object.values(DIAGNOSTIC_RULES),
		...Object.values(STRUCTURAL_DIAGNOSTIC_RULES),
	].map((rule) => [rule.code, rule]),
);

export const XLIDE_DIAGNOSTIC_SOURCE = 'XLIDE';

/** Returns metadata for semantic and structural diagnostic codes. */
export function diagnosticMetadataForCode(
	code: string | undefined,
): DiagnosticRuleMetadata | undefined {
	const normalized = normalizeDiagnosticRuleCode(code);
	if (!normalized) {
		return undefined;
	}
	return DIAGNOSTIC_METADATA_BY_CODE.get(normalized);
}

/** Metadata for every active diagnostic rule, sorted by stable diagnostic code. */
export function allDiagnosticRuleMetadata(): DiagnosticRuleMetadata[] {
	return Array.from(DIAGNOSTIC_METADATA_BY_CODE.values())
		.sort((left, right) => left.code.localeCompare(right.code));
}

/** Severity override choices allowed for one diagnostic code. */
export function allowedDiagnosticSeverityOverridesForCode(
	code: string | undefined,
): readonly DiagnosticSeverityOverride[] {
	const meta = diagnosticMetadataForCode(code);
	if (!meta) {
		return [];
	}
	if (meta.defaultSeverity === 'error') {
		return meta.allowSeverityDowngrade ? ['warning'] : [];
	}
	return ['off'];
}

/** Normalizes one guarded severity override. Invalid or disallowed values are ignored. */
export function normalizeDiagnosticSeverityOverride(
	code: string | undefined,
	value: unknown,
): DiagnosticSeverityOverride | undefined {
	if (!isDiagnosticSeverityOverride(value)) {
		return undefined;
	}
	const allowed = allowedDiagnosticSeverityOverridesForCode(code);
	return allowed.includes(value) ? value : undefined;
}

/** Normalizes a user-provided map keyed by stable diagnostic code. */
export function normalizeDiagnosticSeverityOverrides(
	value: unknown,
): Record<string, DiagnosticSeverityOverride> {
	if (!value || typeof value !== 'object' || Array.isArray(value)) {
		return {};
	}
	const normalized: Record<string, DiagnosticSeverityOverride> = {};
	for (const [rawCode, rawSeverity] of Object.entries(value)) {
		const code = normalizeDiagnosticRuleCode(rawCode);
		const severity = normalizeDiagnosticSeverityOverride(code, rawSeverity);
		if (code && severity) {
			normalized[code] = severity;
		}
	}
	return sortDiagnosticSeverityOverrides(normalized);
}

/** True when a raw value is part of the severity-override vocabulary. */
export function isDiagnosticSeverityOverride(value: unknown): value is DiagnosticSeverityOverride {
	return value === 'off' || value === 'information' || value === 'warning' || value === 'error';
}

export function normalizeDiagnosticRuleCode(code: unknown): string | undefined {
	return typeof code === 'string' ? code.trim().toLowerCase() || undefined : undefined;
}

function sortDiagnosticSeverityOverrides(
	overrides: Record<string, DiagnosticSeverityOverride>,
): Record<string, DiagnosticSeverityOverride> {
	return Object.fromEntries(
		Object.entries(overrides).sort(([left], [right]) => left.localeCompare(right)),
	);
}

/** Rule-level suppression scopes before narrowing by the diagnostic's source position. */
export function diagnosticSuppressionScopesForCode(
	code: string | undefined,
): readonly DiagnosticSuppressionScope[] {
	return diagnosticMetadataForCode(code)?.suppressionScopes ?? DEFAULT_DIAGNOSTIC_SUPPRESSION_SCOPES;
}

/** Problems-panel source label for a diagnostic code. */
export function diagnosticSourceForCode(code: string | undefined): string {
	const meta = diagnosticMetadataForCode(code);
	if (!meta) {
		return XLIDE_DIAGNOSTIC_SOURCE;
	}
	if (meta.vbeCompileEquivalent) {
		return `${XLIDE_DIAGNOSTIC_SOURCE}/VBE`;
	}
	switch (meta.diagnosticKind) {
		case 'deterministic-runtime-error':
			return `${XLIDE_DIAGNOSTIC_SOURCE}/runtime`;
		case 'runtime-risk':
			return `${XLIDE_DIAGNOSTIC_SOURCE}/risk`;
		case 'style-policy':
			return `${XLIDE_DIAGNOSTIC_SOURCE}/style`;
		case 'compile-error':
			return XLIDE_DIAGNOSTIC_SOURCE;
	}
}

/** True for canonical and metadata-expanded XLIDE diagnostic source labels. */
export function isXlideDiagnosticSource(source: string | undefined): boolean {
	return source === XLIDE_DIAGNOSTIC_SOURCE || source?.startsWith(`${XLIDE_DIAGNOSTIC_SOURCE}/`) === true;
}

/** Stable rule-name keys of {@link DIAGNOSTIC_RULES}. */
export type DiagnosticRuleName = keyof typeof DIAGNOSTIC_RULES;
