// GENERATED FILE - do not edit by hand.
//
// The value Access gives each design property of a control it has just
// created, read back through the object model with
// `scripts/measure-access-control-defaults.py`. Regenerate from that.
//
// A design stores a property only where it differs from what the object
// would have anyway, so a reader needs this to show a complete property
// sheet: the control's own record first, then the design's
// control-defaults object for its type, then this.
//
// What the Office theme decides - every colour, font, tint and shade - is
// left out. Access writes those onto the design's own control-defaults
// object, where they are the theme that database actually uses; a table
// here would ship the measuring machine's theme as everybody's.

/** Access's own value for a property, by object type and property name. */
export const ACCESS_CONTROL_DEFAULTS: ReadonlyMap<string, ReadonlyMap<string, string>> =
	new Map([
		['Attachment', new Map([
			['BackStyle', '0'],
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['ControlSource', ''],
			['ControlTipText', ''],
			['DisplayWhen', '0'],
			['Enabled', 'True'],
			['HorizontalAnchor', '0'],
			['Locked', 'False'],
			['OldBorderStyle', '1'],
			['OnClick', ''],
			['PictureAlignment', '2'],
			['PictureTiling', 'False'],
			['ShortcutMenuBar', ''],
			['SpecialEffect', '0'],
			['StatusBarText', ''],
			['TabIndex', '0'],
			['TabStop', 'True'],
			['Tag', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['BoundObjectFrame', new Map([
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['ControlSource', ''],
			['ControlTipText', ''],
			['DisplayWhen', '0'],
			['Enabled', 'True'],
			['HorizontalAnchor', '0'],
			['Locked', 'False'],
			['OldBorderStyle', '1'],
			['OnClick', ''],
			['ShortcutMenuBar', ''],
			['SpecialEffect', '2'],
			['StatusBarText', ''],
			['TabIndex', '1'],
			['TabStop', 'True'],
			['Tag', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['Chart', new Map([
			['BorderLineStyle', '0'],
			['BottomPadding', '30'],
			['CategoryAxisTitle', ''],
			['ChartSubtitle', 'Subtitle'],
			['ChartTitle', 'Chart Title'],
			['ChartTitleFontSize', '14'],
			['ChartType', '0'],
			['HasAxisTitles', 'True'],
			['HasLegend', 'True'],
			['HasSubtitle', 'False'],
			['HasTitle', 'True'],
			['HorizontalAnchor', '0'],
			['LegendPosition', '1'],
			['LinkChildFields', ''],
			['OldBorderStyle', '0'],
			['PrimaryValuesAxisTitle', ''],
			['RowSource', ''],
			['TabIndex', '2'],
			['TopPadding', '30'],
		])],
		['CheckBox', new Map([
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['ControlSource', ''],
			['ControlTipText', ''],
			['DefaultValue', ''],
			['DisplayWhen', '0'],
			['Enabled', 'True'],
			['HorizontalAnchor', '0'],
			['Locked', 'False'],
			['OldBorderStyle', '1'],
			['OnClick', ''],
			['ReadingOrder', '0'],
			['ShortcutMenuBar', ''],
			['SpecialEffect', '0'],
			['StatusBarText', ''],
			['TabIndex', '3'],
			['TabStop', 'True'],
			['Tag', ''],
			['TripleState', 'False'],
			['ValidationRule', ''],
			['ValidationText', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['ComboBox', new Map([
			['AllowAutoCorrect', 'True'],
			['AutoExpand', 'True'],
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['BottomMargin', '0'],
			['BoundColumn', '1'],
			['CanGrow', 'False'],
			['CanShrink', 'False'],
			['ColumnHeads', 'False'],
			['ColumnWidths', ''],
			['ControlSource', ''],
			['ControlTipText', ''],
			['DecimalPlaces', '255'],
			['DefaultValue', ''],
			['DisplayWhen', '0'],
			['Enabled', 'True'],
			['FontItalic', 'False'],
			['FontUnderline', 'False'],
			['Format', ''],
			['HorizontalAnchor', '0'],
			['IMEMode', '0'],
			['InputMask', ''],
			['KeyboardLanguage', '0'],
			['LeftMargin', '0'],
			['LimitToList', 'False'],
			['ListRows', '16'],
			['ListWidth', '0'],
			['Locked', 'False'],
			['NumeralShapes', '0'],
			['OldBorderStyle', '1'],
			['OnClick', ''],
			['ReadingOrder', '0'],
			['RightMargin', '0'],
			['RowSource', ''],
			['RowSourceType', 'Table/Query'],
			['ScrollBarAlign', '0'],
			['ShortcutMenuBar', ''],
			['SpecialEffect', '0'],
			['StatusBarText', ''],
			['TabIndex', '4'],
			['TabStop', 'True'],
			['Tag', ''],
			['TextAlign', '0'],
			['TopMargin', '0'],
			['ValidationRule', ''],
			['ValidationText', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['CommandButton', new Map([
			['Alignment', '2'],
			['AutoRepeat', 'False'],
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['BottomPadding', '30'],
			['Cancel', 'False'],
			['Caption', ''],
			['ControlTipText', ''],
			['CursorOnHover', '0'],
			['Default', 'False'],
			['DisplayWhen', '0'],
			['Enabled', 'True'],
			['FontItalic', 'False'],
			['FontUnderline', 'False'],
			['GridlineStyleTop', '0'],
			['GridlineWidthTop', '1'],
			['HelpContextId', '0'],
			['HorizontalAnchor', '0'],
			['HyperlinkAddress', ''],
			['HyperlinkSubAddress', ''],
			['LeftPadding', '30'],
			['OldBorderStyle', '1'],
			['OnClick', ''],
			['PictureCaptionArrangement', '0'],
			['PictureType', '0'],
			['ReadingOrder', '0'],
			['RightPadding', '30'],
			['ShortcutMenuBar', ''],
			['StatusBarText', ''],
			['TabIndex', '5'],
			['TabStop', 'True'],
			['Tag', ''],
			['TextFontCharSet', '0'],
			['TopPadding', '30'],
			['Transparent', 'False'],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['CustomControl', new Map([
			['OldBorderStyle', '1'],
			['TabIndex', '6'],
		])],
		['Detail', new Map([
			['AutoHeight', 'True'],
			['CanGrow', 'False'],
		])],
		['EdgeBrowser', new Map([
			['BottomPadding', '30'],
			['HorizontalAnchor', '0'],
			['OldBorderStyle', '1'],
			['OnDocumentComplete', ''],
			['OnNavigateError', ''],
			['ScrollLeft', '0'],
			['ScrollTop', '0'],
			['TabIndex', '7'],
			['TopPadding', '30'],
		])],
		['Form', new Map([
			['Caption', ''],
			['PictureAlignment', '2'],
		])],
		['Image', new Map([
			['BackStyle', '0'],
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['ControlSource', ''],
			['ControlTipText', ''],
			['DisplayWhen', '0'],
			['HorizontalAnchor', '0'],
			['OldBorderStyle', '0'],
			['OnClick', ''],
			['PictureAlignment', '2'],
			['PictureTiling', 'False'],
			['ShortcutMenuBar', ''],
			['SpecialEffect', '0'],
			['Tag', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['Label', new Map([
			['BackStyle', '0'],
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['BottomMargin', '0'],
			['Caption', ''],
			['ControlTipText', ''],
			['DisplayWhen', '0'],
			['FontItalic', 'False'],
			['FontUnderline', 'False'],
			['HorizontalAnchor', '0'],
			['LeftMargin', '0'],
			['LineSpacing', '0'],
			['NumeralShapes', '0'],
			['OldBorderStyle', '0'],
			['OnClick', ''],
			['ReadingOrder', '0'],
			['RightMargin', '0'],
			['ShortcutMenuBar', ''],
			['SpecialEffect', '0'],
			['Tag', ''],
			['TextAlign', '0'],
			['TopMargin', '0'],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['Line', new Map([
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['DisplayWhen', '0'],
			['HorizontalAnchor', '0'],
			['OldBorderStyle', '1'],
			['SpecialEffect', '0'],
			['Tag', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['ListBox', new Map([
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['BoundColumn', '1'],
			['ColumnHeads', 'False'],
			['ColumnWidths', ''],
			['ControlSource', ''],
			['ControlTipText', ''],
			['DefaultValue', ''],
			['DisplayWhen', '0'],
			['Enabled', 'True'],
			['FontItalic', 'False'],
			['FontUnderline', 'False'],
			['HorizontalAnchor', '0'],
			['IMEMode', '0'],
			['Locked', 'False'],
			['MultiSelect', '0'],
			['NumeralShapes', '0'],
			['OldBorderStyle', '1'],
			['OnClick', ''],
			['ReadingOrder', '0'],
			['RowSource', ''],
			['RowSourceType', 'Table/Query'],
			['ScrollBarAlign', '0'],
			['ShortcutMenuBar', ''],
			['SpecialEffect', '0'],
			['StatusBarText', ''],
			['TabIndex', '9'],
			['TabStop', 'True'],
			['Tag', ''],
			['ValidationRule', ''],
			['ValidationText', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['NavigationControl', new Map([
			['BorderLineStyle', '0'],
			['BorderWidth', '1'],
			['BottomPadding', '0'],
			['GridlineStyleBottom', '0'],
			['GridlineStyleLeft', '0'],
			['GridlineStyleRight', '0'],
			['GridlineStyleTop', '0'],
			['GridlineWidthBottom', '1'],
			['GridlineWidthLeft', '1'],
			['GridlineWidthRight', '1'],
			['GridlineWidthTop', '1'],
			['HelpContextId', '0'],
			['HorizontalAnchor', '2'],
			['LeftPadding', '30'],
			['OldBorderStyle', '0'],
			['RightPadding', '30'],
			['ShortcutMenuBar', ''],
			['Span', '0'],
			['TopPadding', '0'],
		])],
		['ObjectFrame', new Map([
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['ControlTipText', ''],
			['DisplayWhen', '0'],
			['HorizontalAnchor', '2'],
			['OldBorderStyle', '1'],
			['OnClick', ''],
			['ShortcutMenuBar', ''],
			['SpecialEffect', '2'],
			['TabIndex', '1'],
			['TabStop', 'True'],
			['Tag', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['OptionButton', new Map([
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['ControlSource', ''],
			['ControlTipText', ''],
			['DefaultValue', ''],
			['DisplayWhen', '0'],
			['Enabled', 'True'],
			['HorizontalAnchor', '0'],
			['Locked', 'False'],
			['OldBorderStyle', '1'],
			['OnClick', ''],
			['ReadingOrder', '0'],
			['ShortcutMenuBar', ''],
			['SpecialEffect', '0'],
			['StatusBarText', ''],
			['TabIndex', '13'],
			['TabStop', 'True'],
			['Tag', ''],
			['TripleState', 'False'],
			['ValidationRule', ''],
			['ValidationText', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['OptionGroup', new Map([
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['ControlSource', ''],
			['ControlTipText', ''],
			['DefaultValue', ''],
			['DisplayWhen', '0'],
			['Enabled', 'True'],
			['HorizontalAnchor', '0'],
			['Locked', 'False'],
			['OldBorderStyle', '1'],
			['OnClick', ''],
			['ShortcutMenuBar', ''],
			['SpecialEffect', '3'],
			['StatusBarText', ''],
			['TabIndex', '14'],
			['TabStop', 'True'],
			['Tag', ''],
			['ValidationRule', ''],
			['ValidationText', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['Page', new Map([
			['Caption', ''],
		])],
		['Rectangle', new Map([
			['BackStyle', '0'],
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['DisplayWhen', '0'],
			['HorizontalAnchor', '0'],
			['OldBorderStyle', '1'],
			['OnClick', ''],
			['SpecialEffect', '3'],
			['Tag', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['Report', new Map([
			['Caption', ''],
			['PictureAlignment', '2'],
		])],
		['Subform', new Map([
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['BottomPadding', '30'],
			['CanShrink', 'False'],
			['DisplayWhen', '0'],
			['Enabled', 'True'],
			['HorizontalAnchor', '0'],
			['LeftPadding', '30'],
			['LinkChildFields', ''],
			['LinkMasterFields', ''],
			['Locked', 'False'],
			['OldBorderStyle', '1'],
			['RightPadding', '30'],
			['SpecialEffect', '0'],
			['StatusBarText', ''],
			['TabIndex', '15'],
			['TabStop', 'True'],
			['Tag', ''],
			['TopPadding', '30'],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['Tab', new Map([
			['BorderLineStyle', '0'],
			['DisplayWhen', '0'],
			['Enabled', 'True'],
			['FontItalic', 'False'],
			['FontUnderline', 'False'],
			['HorizontalAnchor', '0'],
			['OldBorderStyle', '1'],
			['OnClick', ''],
			['ShortcutMenuBar', ''],
			['StatusBarText', ''],
			['TabIndex', '16'],
			['TabStop', 'True'],
			['Tag', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['TextBox', new Map([
			['AllowAutoCorrect', 'True'],
			['BackStyle', '1'],
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['BottomMargin', '0'],
			['BottomPadding', '30'],
			['CanGrow', 'False'],
			['CanShrink', 'False'],
			['ControlSource', ''],
			['ControlTipText', ''],
			['DecimalPlaces', '255'],
			['DefaultValue', ''],
			['DisplayAsHyperlink', '0'],
			['DisplayWhen', '0'],
			['Enabled', 'True'],
			['FilterLookup', '1'],
			['FontItalic', 'False'],
			['FontUnderline', 'False'],
			['Format', ''],
			['HorizontalAnchor', '0'],
			['IMEMode', '0'],
			['InputMask', ''],
			['IsHyperlink', 'False'],
			['KeyboardLanguage', '0'],
			['LeftMargin', '0'],
			['LineSpacing', '0'],
			['Locked', 'False'],
			['NumeralShapes', '0'],
			['OldBorderStyle', '1'],
			['OnClick', ''],
			['ReadingOrder', '0'],
			['RightMargin', '0'],
			['ScrollBarAlign', '0'],
			['ScrollBars', '0'],
			['ShortcutMenuBar', ''],
			['ShowDatePicker', '1'],
			['SpecialEffect', '0'],
			['StatusBarText', ''],
			['TabIndex', '17'],
			['TabStop', 'True'],
			['Tag', ''],
			['TextAlign', '0'],
			['TextFormat', '0'],
			['TopMargin', '0'],
			['TopPadding', '30'],
			['ValidationRule', ''],
			['ValidationText', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['ToggleButton', new Map([
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['BottomPadding', '30'],
			['Caption', ''],
			['ControlSource', ''],
			['ControlTipText', ''],
			['DefaultValue', ''],
			['DisplayWhen', '0'],
			['Enabled', 'True'],
			['FontItalic', 'False'],
			['FontUnderline', 'False'],
			['HorizontalAnchor', '0'],
			['LeftPadding', '30'],
			['Locked', 'False'],
			['OldBorderStyle', '0'],
			['OnClick', ''],
			['ReadingOrder', '0'],
			['RightPadding', '30'],
			['ShortcutMenuBar', ''],
			['StatusBarText', ''],
			['TabIndex', '18'],
			['TabStop', 'True'],
			['Tag', ''],
			['TopPadding', '30'],
			['TripleState', 'False'],
			['ValidationRule', ''],
			['ValidationText', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
		['WebBrowser', new Map([
			['BorderLineStyle', '0'],
			['BorderWidth', '0'],
			['ControlSource', ''],
			['ControlTipText', ''],
			['DisplayWhen', '0'],
			['Enabled', 'True'],
			['HorizontalAnchor', '0'],
			['OldBorderStyle', '1'],
			['SpecialEffect', '0'],
			['StatusBarText', ''],
			['TabIndex', '19'],
			['TabStop', 'True'],
			['Tag', ''],
			['VerticalAnchor', '0'],
			['Visible', 'True'],
		])],
	]);
