import {expect,it} from 'vitest';
import {checkArgumentTypes} from '../src/analyzer/diagnostics/rules/argumentTypes';
import {parseModule} from '../src/analyzer/parser/parseModule';
import {buildModuleSymbols} from '../src/analyzer/symbols/buildModuleSymbols';
import {forEachStatement} from '../src/analyzer/parser/statementWalk';
import {analyzeModule} from '../src/analyzer/diagnostics/analyzeModule';
import type {VbaProjectClassMembers} from '../src/analyzer/symbols/symbolModel';
type Mode='declared'|'held'|'new';const modes:Mode[]=['declared','held','new'];
function surface(name:string,implemented:string[]=[]):VbaProjectClassMembers{return {name,moduleName:name,kind:'class',exhaustive:true,members:[],implements:implemented};}
function sourceFor(mode:Mode,count:number,procedures=false){return ['Option Explicit','Sub Take(ByVal target As Class1)','End Sub',...Array.from({length:procedures?count:1},(_,i)=>['Sub Go'+i+'(ByVal actual As '+(mode==='held'?'Object':'Class2')+')',...(mode==='held'?['Set actual = New Class2']:[]),...Array.from({length:procedures?1:count},()=>mode==='new'?'Take New Class2':'Take actual'),'End Sub'].join('\n')),''].join('\n');}
function run(source:string,classes:VbaProjectClassMembers[]){const errors:string[]=[];const out=analyzeModule(source,{projectClassMembers:classes,onInternalError:e=>errors.push(String(e))});expect(errors).toEqual([]);return out;}
function runRule(source:string,classes:VbaProjectClassMembers[]){const mod=parseModule(source),symbols=buildModuleSymbols('M','standard',source,{parsedModule:mod}),out:unknown[][]=[],factory=checkArgumentTypes(source,symbols,undefined,undefined,{projectClassMembers:classes},(...args)=>out.push(args));for(const p of mod.members){if(p.kind!=='Procedure'){continue;}const visit=factory(p);if(visit){forEachStatement(p.body,visit);}}return out;}
for(const mode of modes){
 it.each([10,100,1000])('bounds type and interface work at %i arguments: '+mode,count=>{let names=0,reads=0;const impl=new Proxy(Array.from({length:count},(_,i)=>i===count-1?'Class1':'Other'+i),{get(t,k,r){if(typeof k==='string'&&/^(0|[1-9]\d*)$/.test(k)){reads++;}return Reflect.get(t,k,r);}});const classes=[surface('Class1'),surface('Class2',impl),...Array.from({length:count},(_,i)=>surface('Extra'+i))];for(const c of classes){const name=c.name;Object.defineProperty(c,'name',{get(){names++;return name;}});}expect(run(sourceFor(mode,count),classes)).toEqual([]);expect(names).toBeLessThanOrEqual(count*20+100);expect(reads).toBeLessThanOrEqual(count*3);});
 it('shares '+mode+' queries across procedures',()=>{let reads=0,names=0;const impl=new Proxy(Array.from({length:100},(_,i)=>i===99?'Class1':'Other'+i),{get(t,k,r){if(typeof k==='string'&&/^(0|[1-9]\d*)$/.test(k)){reads++;}return Reflect.get(t,k,r);}});const classes=[surface('Class1'),surface('Class2',impl),...Array.from({length:100},(_,i)=>surface('Extra'+i))];for(const c of classes){const name=c.name;Object.defineProperty(c,'name',{get(){names++;return name;}});}expect(runRule(sourceFor(mode,100,true),classes)).toEqual([]);expect(names).toBeLessThanOrEqual(4000);expect(reads).toBeLessThanOrEqual(300);});
 it('preserves '+mode+' incompatible-value behavior and refreshes interfaces',()=>{const source=sourceFor(mode,1),classes=[surface('Class1'),surface('Class2')];const before=run(source,classes);expect(before.length).toBe(mode==='declared'?0:1);if(mode!=='declared'){expect(before[0].code).toBe('argument-type-mismatch');expect(before[0].message).toContain('This object type is not compatible with Class1.');const text=mode==='new'?'New Class2':'actual',start=source.lastIndexOf(text);expect(before[0].span).toEqual({start,end:start+text.length});}classes[1].implements=['cLaSs1'];expect(run(source,classes)).toEqual([]);classes[1].implements=[];expect(run(source,classes)).toEqual(before);});
}
it.each(['statement','call','expression','member-expression','member-statement'] as const)('shares interfaces for %s calls',form=>{
 let reads=0;const names=new Proxy(Array.from({length:100},(_,i)=>i===99?'Class1':'Other'+i),{get(t,k,r){if(typeof k==='string'&&/^(0|[1-9]\d*)$/.test(k)){reads++;}return Reflect.get(t,k,r);}});
 const classes=[surface('Class1'),surface('Class2',names),surface('Holder')];classes[2].members=[{name:'Take',kind:'method',moduleName:'Holder',signature:'Take(ByVal target As Class1) As Long',returns:'Long'}];
 const call=form==='statement'?'Take New Class2':form==='call'?'Call Take(New Class2)':form==='expression'?'Debug.Print Take(New Class2)':form==='member-expression'?'Debug.Print holder.Take(New Class2)':'holder.Take New Class2';
 const source=['Option Explicit','Function Take(ByVal target As Class1) As Long','Take = 1','End Function','Sub Go(ByVal holder As Holder)',...Array.from({length:100},()=>call),'End Sub',''].join('\n');expect(run(source,classes)).toEqual([]);expect(reads).toBeLessThanOrEqual(300);
});
