import {expect,it} from 'vitest';
import {checkObjectDefaultValues} from '../src/analyzer/diagnostics/rules/objectValues';
import {checkStatementForms} from '../src/analyzer/diagnostics/rules/statementForms';
import {createObjectDefaultQueries,objectLetAssignmentVerdict,objectValueNeedsIndex} from '../src/analyzer/diagnostics/typeInference';
import {parseModule} from '../src/analyzer/parser/parseModule';
import {buildModuleSymbols} from '../src/analyzer/symbols/buildModuleSymbols';
import {forEachStatement} from '../src/analyzer/parser/statementWalk';
import type {VbaProjectClassMembers} from '../src/analyzer/symbols/symbolModel';
function surface(name:string,kind:VbaProjectClassMembers['kind']='class',signature?:string,exhaustive=true):VbaProjectClassMembers{return {name,moduleName:name,kind,exhaustive,members:signature===undefined?[]:[{name:'Item',kind:'property',moduleName:name,returns:'Long',defaultMember:true,signature}]};}
function run(source:string,classes:VbaProjectClassMembers[],kind:'values'|'statements'){const mod=parseModule(source),symbols=buildModuleSymbols('M','standard',source,{parsedModule:mod}),out:unknown[][]=[];if(kind==='statements'){checkStatementForms(source,mod,symbols,undefined,undefined,(...v)=>out.push(v),{projectClassMembers:classes});}else{const factory=checkObjectDefaultValues(source,symbols,{projectClassMembers:classes},(...v)=>out.push(v));for(const p of mod.members){if(p.kind!=='Procedure'){continue;}const visit=factory(p);if(visit){forEachStatement(p.body,visit);}}}return out;}
for(const kind of ['values','statements'] as const)for(const distinct of [false,true])it.each([10,100,1000])('bounds '+kind+' default queries at %i procedures, distinct='+distinct,count=>{
 let names=0;const classes=Array.from({length:count+1},(_,i)=>({...surface('Class'+i),get name(){names++;return 'Class'+i;}}));const source=['Option Explicit',...Array.from({length:count},(_,i)=>'Sub P'+i+'(ByVal actor As Class'+(distinct?i:0)+')\nDebug.Print actor\nEnd Sub'),''].join('\n');let from=0;const expected=kind==='statements'?[]:Array.from({length:count},(_,i)=>{const start=source.indexOf('Debug.Print actor',from)+12;from=start+5;return ['objectDefaultValue',"'actor' is a Class"+(distinct?i:0)+", which has no default member, so it has no value to read here. This will raise Run-time error '438': Object doesn't support this property or method, or '91' while it is Nothing.",{start,end:start+5}];});expect(run(source,classes,kind)).toEqual(expected);expect(names).toBeLessThanOrEqual(count*15+100);
});
it.each([
 ['Object','lets',false],['Variant','unknown',false],['Collection','argument',true],['Worksheet','noDefault',false],['Range','lets',false],['Missing','unknown',false],['Class1','noDefault',false],['cLaSs1','noDefault',false],
] as const)('preserves %s default verdict and index requirement', (type,verdict,index)=>{const ctx={projectClassMembers:[surface('Class1')]},q=createObjectDefaultQueries(ctx);expect(objectLetAssignmentVerdict(type,ctx)).toBe(verdict);expect(q.verdictFor(type)).toBe(verdict);expect(objectValueNeedsIndex(type,ctx)).toBe(index);expect(q.needsIndex(type)).toBe(index);});
it.each(['class','document','userform','userType','enum','standardModule'] as const)('preserves first %s surface default metadata',kind=>{const ctx={projectClassMembers:[surface('CLASS1',kind,'Item()'),surface('Class1')]};const expected=kind==='class'||kind==='document'||kind==='userform'?'unknown':'lets';expect(objectLetAssignmentVerdict('Class1',ctx)).toBe(expected);expect(createObjectDefaultQueries(ctx).verdictFor('Class1')).toBe(expected);});
it('preserves an incomplete first class rather than promoting a duplicate',()=>{const source='Sub Go(ByVal actor As Class1)\nDebug.Print actor(1)\nEnd Sub\n',classes=[surface('Class1','class',undefined,false),surface('CLASS1')];expect(run(source,classes,'values')).toEqual([]);});
it('refreshes verdict and first-surface facts in a new query',()=>{const classes=[surface('Class1')],ctx={projectClassMembers:classes};expect(createObjectDefaultQueries(ctx).verdictFor('Class1')).toBe('noDefault');classes[0].members=surface('Class1','class','Item()').members;expect(createObjectDefaultQueries(ctx).verdictFor('Class1')).toBe('lets');classes.unshift(surface('CLASS1','enum',undefined,false));expect(createObjectDefaultQueries(ctx).verdictFor('Class1')).toBe('unknown');});
it('keeps unconsulted project member arrays lazy',()=>{const extra=surface('Extra');Object.defineProperty(extra,'members',{get(){throw Error('unused members');}});expect(createObjectDefaultQueries({projectClassMembers:[surface('Class1'),extra]}).verdictFor('Class1')).toBe('noDefault');});
