import {expect,it} from 'vitest';
import {analyzeModule} from '../src/analyzer/diagnostics/analyzeModule';
import {checkObjectVariableNotSet} from '../src/analyzer/diagnostics/rules/objectState';
import {parseModule} from '../src/analyzer/parser/parseModule';
import {buildModuleSymbols} from '../src/analyzer/symbols/buildModuleSymbols';
import type {VbaProjectClassMembers} from '../src/analyzer/symbols/symbolModel';
function surface(name:string,kind:VbaProjectClassMembers['kind']='class'):VbaProjectClassMembers{return {name,moduleName:name,kind,exhaustive:true,members:[{name:'Value',kind:'property',moduleName:name,returns:'Long'}]};}
function sourceFor(type:string){return 'Option Explicit\nSub Touch(ByVal actor As '+type+')\nDebug.Print actor.Value\nEnd Sub\nSub Go()\nDim value As Object\nTouch value\nEnd Sub\n';}
function run(source:string,classes:VbaProjectClassMembers[],mod=parseModule(source)){const symbols=buildModuleSymbols('M','standard',source,{parsedModule:mod}),out:unknown[][]=[];checkObjectVariableNotSet(source,mod,symbols,{projectClassMembers:classes},undefined,(...v)=>out.push(v));return out;}
function expected(source:string){const start=source.lastIndexOf('value');return [['objectVariableNotSet',"Object variable 'value' is Nothing, and Touch reads 'actor.Value' from it first. This will raise Run-time error '91': Object variable or With block variable not set.",{start,end:start+5}]];}
for(const distinct of [false,true])it.each([10,100,1000])('bounds full-module parameter classification at %i procedures, distinct='+distinct,count=>{let names=0;const classes=Array.from({length:count+1},(_,i)=>({...surface('Class'+i),get name(){names++;return 'Class'+i;}}));const source=['Option Explicit',...Array.from({length:count},(_,i)=>'Sub P'+i+'(ByVal actor As Class'+(distinct?i:0)+')\nEnd Sub'),''].join('\n');const errors:string[]=[];expect(analyzeModule(source,{projectClassMembers:classes,onInternalError:e=>errors.push(String(e))})).toEqual([]);expect(errors).toEqual([]);expect(names).toBeLessThanOrEqual(count*8+30);});
it.each(['class','document','userform','userType','enum','standardModule'] as const)('preserves %s object-type eligibility',kind=>{const source=sourceFor('Class1');expect(run(source,[surface('Class1',kind)])).toEqual(['class','document','userform'].includes(kind)?expected(source):[]);});
it.each([['Object',true],['Variant',false],['Collection',true],['Worksheet',true],['Missing',false],['Long',false],['cLaSs1',true]] as const)('preserves %s parameter classification', (type,known)=>{const source=sourceFor(type);expect(run(source,[surface('Class1')])).toEqual(known?expected(source):[]);});
it('refreshes classification under a new context with the same retained module AST',()=>{const source=sourceFor('Class1'),mod=parseModule(source),classes:VbaProjectClassMembers[]=[];expect(run(source,classes,mod)).toEqual([]);classes.push(surface('Class1'));expect(run(source,classes,mod)).toEqual(expected(source));classes.push(surface('CLASS1'));expect(run(source,classes,mod)).toEqual([]);});
