// Worksheet function names, by how an OOXML file stores a formula using them.
//
// Functions newer than the ECMA-376 predefined set are stored with a prefix
// that Excel's formula bar hides: _xlfn., and _xlfn._xlws. for the few that
// only work on a worksheet. The list is the [MS-XLSX] 2.2.2 future-function
// table and grammar plus the functions Excel 16 was seen storing with a
// prefix. Every entry Excel 16 knows was checked by having it store a formula
// that uses it; COPILOT, LONGTEXT, PY, PQSOURCE, QUERYSTRING and the PYTHON_
// functions rest on the specification alone.

const WORKSHEET_ONLY = new Set(['FILTER', 'PY', 'SORT']);

const FUTURE = `
ACOT ACOTH AGGREGATE ANCHORARRAY ARABIC ARRAYTOTEXT BASE BETA.DIST BETA.INV BINOM.DIST
BINOM.DIST.RANGE BINOM.INV BITAND BITLSHIFT BITOR BITRSHIFT BITXOR BYCOL BYROW CEILING.MATH
CEILING.PRECISE CHISQ.DIST CHISQ.DIST.RT CHISQ.INV CHISQ.INV.RT CHISQ.TEST CHOOSECOLS CHOOSEROWS
COMBINA CONCAT CONFIDENCE.NORM CONFIDENCE.T COPILOT COT COTH COVARIANCE.P COVARIANCE.S CSC CSCH DAYS
DECIMAL DETECTLANGUAGE DROP ENCODEURL ERF.PRECISE ERFC.PRECISE EXPAND EXPON.DIST F.DIST F.DIST.RT
F.INV F.INV.RT F.TEST FIELDVALUE FILTER FILTERXML FLOOR.MATH FLOOR.PRECISE FORECAST.ETS
FORECAST.ETS.CONFINT FORECAST.ETS.SEASONALITY FORECAST.ETS.STAT FORECAST.LINEAR FORMULATEXT GAMMA
GAMMA.DIST GAMMA.INV GAMMALN.PRECISE GAUSS GROUPBY HSTACK HYPGEOM.DIST IFNA IFS IMAGE IMCOSH IMCOT
IMCSC IMCSCH IMPORTCSV IMPORTTEXT IMSEC IMSECH IMSINH IMTAN ISFORMULA ISOMITTED ISOWEEKNUM LAMBDA
LET LOGNORM.DIST LOGNORM.INV LONGTEXT MAKEARRAY MAP MAXIFS MINIFS MODE.MULT MODE.SNGL MUNIT
NEGBINOM.DIST NORM.DIST NORM.INV NORM.S.DIST NORM.S.INV NUMBERVALUE PDURATION PERCENTILE.EXC
PERCENTILE.INC PERCENTOF PERCENTRANK.EXC PERCENTRANK.INC PERMUTATIONA PHI PIVOTBY POISSON.DIST
PQSOURCE PY PYTHON_STR PYTHON_TYPE PYTHON_TYPENAME QUARTILE.EXC QUARTILE.INC QUERYSTRING RANDARRAY
RANK.AVG RANK.EQ REDUCE REGEXEXTRACT REGEXREPLACE REGEXTEST RRI SCAN SEC SECH SEQUENCE SHEET SHEETS
SINGLE SKEW.P SORT SORTBY STDEV.P STDEV.S STOCKHISTORY SWITCH T.DIST T.DIST.2T T.DIST.RT T.INV
T.INV.2T T.TEST TAKE TEXTAFTER TEXTBEFORE TEXTJOIN TEXTSPLIT TOCOL TOROW TRANSLATE TRIMRANGE UNICHAR
UNICODE UNIQUE VALUETOTEXT VAR.P VAR.S VSTACK WEBSERVICE WEIBULL.DIST WRAPCOLS WRAPROWS XLOOKUP
XMATCH XOR Z.TEST
`;

/** Future functions: the name as typed, and the name the file stores. */
export const FUTURE_FUNCTIONS: ReadonlyMap<string, string> = new Map(
	FUTURE.split(/\s+/).filter(Boolean).map((name) => [
		name,
		`${WORKSHEET_ONLY.has(name) ? '_xlfn._xlws.' : '_xlfn.'}${name}`,
	]),
);

/**
 * Built-in functions Excel stores as an eta lambda (`_xleta.SUM`) when a
 * formula names one without calling it, as in `GROUPBY(A2:A9, B2:B9, SUM)`.
 * Checked by having Excel store `BYROW(range, NAME)` for each candidate.
 */
export const ETA_FUNCTIONS: ReadonlySet<string> = new Set(`
ABS ACCRINT ACCRINTM ACOS ACOSH ACOT ACOTH ADDRESS AGGREGATE AMORDEGRC AMORLINC ANCHORARRAY AND
ARABIC AREAS ARRAYTOTEXT ASC ASIN ASINH ATAN ATAN2 ATANH AVEDEV AVERAGE AVERAGEA AVERAGEIF
AVERAGEIFS BAHTTEXT BASE BESSELI BESSELJ BESSELK BESSELY BETA.DIST BETA.INV BETADIST BETAINV BIN2DEC
BIN2HEX BIN2OCT BINOM.DIST BINOM.DIST.RANGE BINOM.INV BINOMDIST BITAND BITLSHIFT BITOR BITRSHIFT
BITXOR BYCOL BYROW CEILING CEILING.MATH CEILING.PRECISE CELL CHIDIST CHIINV CHISQ.DIST CHISQ.DIST.RT
CHISQ.INV CHISQ.INV.RT CHISQ.TEST CHITEST CHOOSE CHOOSECOLS CHOOSEROWS CLEAN CODE COLUMN COLUMNS
COMBIN COMBINA COMPLEX CONCAT CONCATENATE CONFIDENCE CONFIDENCE.NORM CONFIDENCE.T CONVERT CORREL COS
COSH COT COTH COUNT COUNTA COUNTBLANK COUNTIF COUNTIFS COUPDAYBS COUPDAYS COUPDAYSNC COUPNCD COUPNUM
COUPPCD COVAR COVARIANCE.P COVARIANCE.S CRITBINOM CSC CSCH CUBEKPIMEMBER CUBEMEMBER
CUBEMEMBERPROPERTY CUBERANKEDMEMBER CUBESET CUBESETCOUNT CUBEVALUE CUMIPMT CUMPRINC DATE DATEDIF
DATESTRING DATEVALUE DAVERAGE DAY DAYS DAYS360 DB DBCS DCOUNT DCOUNTA DDB DEC2BIN DEC2HEX DEC2OCT
DECIMAL DEGREES DELTA DETECTLANGUAGE DEVSQ DGET DISC DMAX DMIN DOLLAR DOLLARDE DOLLARFR DPRODUCT
DROP DSTDEV DSTDEVP DSUM DURATION DVAR DVARP EDATE EFFECT ENCODEURL EOMONTH ERF ERF.PRECISE ERFC
ERFC.PRECISE ERROR.TYPE EVEN EXACT EXP EXPAND EXPON.DIST EXPONDIST F.DIST F.DIST.RT F.INV F.INV.RT
F.TEST FACT FACTDOUBLE FDIST FIELDVALUE FILTER FILTERXML FIND FINDB FINV FISHER FISHERINV FIXED
FLOOR FLOOR.MATH FLOOR.PRECISE FORECAST FORECAST.ETS FORECAST.ETS.CONFINT FORECAST.ETS.SEASONALITY
FORECAST.ETS.STAT FORECAST.LINEAR FORMULATEXT FREQUENCY FTEST FV FVSCHEDULE GAMMA GAMMA.DIST
GAMMA.INV GAMMADIST GAMMAINV GAMMALN GAMMALN.PRECISE GAUSS GCD GEOMEAN GESTEP GETPIVOTDATA GROUPBY
GROWTH HARMEAN HEX2BIN HEX2OCT HLOOKUP HOUR HSTACK HYPERLINK HYPGEOM.DIST HYPGEOMDIST IF IFERROR
IFNA IFS IMABS IMAGE IMAGINARY IMARGUMENT IMCONJUGATE IMCOS IMCOSH IMCOT IMCSC IMCSCH IMDIV IMEXP
IMLN IMLOG10 IMLOG2 IMPORTCSV IMPORTTEXT IMPOWER IMPRODUCT IMREAL IMSEC IMSECH IMSIN IMSINH IMSQRT
IMSUB IMSUM IMTAN INDEX INDIRECT INFO INT INTERCEPT INTRATE IPMT IRR ISBLANK ISERR ISERROR ISEVEN
ISFORMULA ISLOGICAL ISNA ISNONTEXT ISNUMBER ISODD ISOMITTED ISOWEEKNUM ISPMT ISREF ISTEXT
ISTHAIDIGIT KURT LARGE LCM LEFT LEFTB LEN LENB LINEST LN LOG LOGEST LOGINV LOGNORM.DIST LOGNORM.INV
LOGNORMDIST LOOKUP LOWER MAKEARRAY MAP MATCH MAX MAXA MAXIFS MDETERM MDURATION MEDIAN MID MIDB MIN
MINA MINIFS MINUTE MINVERSE MIRR MMULT MOD MODE MODE.MULT MODE.SNGL MONTH MROUND MULTINOMIAL MUNIT N
NA NEGBINOM.DIST NEGBINOMDIST NETWORKDAYS NOMINAL NORM.DIST NORM.INV NORM.S.DIST NORM.S.INV NORMDIST
NORMINV NORMSDIST NORMSINV NOT NOW NPER NPV NUMBERSTRING NUMBERVALUE OCT2BIN OCT2DEC OCT2HEX ODD
ODDFPRICE ODDFYIELD ODDLPRICE ODDLYIELD OFFSET OR PDURATION PEARSON PERCENTILE PERCENTILE.EXC
PERCENTILE.INC PERCENTOF PERCENTRANK PERCENTRANK.EXC PERCENTRANK.INC PERMUT PERMUTATIONA PHI
PHONETIC PI PIVOTBY PMT POISSON POISSON.DIST POWER PPMT PRICE PRICEDISC PRICEMAT PROB PRODUCT PROPER
PV PY QUARTILE QUARTILE.EXC QUARTILE.INC QUOTIENT RADIANS RAND RANDARRAY RANDBETWEEN RANK RANK.AVG
RANK.EQ RATE RECEIVED REDUCE REGEXEXTRACT REGEXREPLACE REGEXTEST REPLACE REPLACEB REPT RIGHT RIGHTB
ROMAN ROUND ROUNDBAHTDOWN ROUNDBAHTUP ROUNDDOWN ROUNDUP ROW ROWS RRI RSQ RTD SCAN SEARCH SEARCHB SEC
SECH SECOND SEQUENCE SERIESSUM SHEET SHEETS SIGN SIN SINGLE SINH SKEW SKEW.P SLN SLOPE SMALL SORT
SORTBY SQRT SQRTPI STANDARDIZE STDEV STDEV.P STDEV.S STDEVA STDEVP STDEVPA STEYX STOCKHISTORY
SUBSTITUTE SUBTOTAL SUM SUMIF SUMIFS SUMPRODUCT SUMSQ SUMX2MY2 SUMX2PY2 SUMXMY2 SWITCH SYD T T.DIST
T.DIST.2T T.DIST.RT T.INV T.INV.2T T.TEST TAKE TAN TANH TBILLEQ TBILLPRICE TBILLYIELD TDIST TEXT
TEXTAFTER TEXTBEFORE TEXTJOIN TEXTSPLIT THAIDAYOFWEEK THAIDIGIT THAIMONTHOFYEAR THAINUMSOUND
THAINUMSTRING THAISTRINGLENGTH THAIYEAR TIME TIMEVALUE TINV TOCOL TODAY TOROW TRANSLATE TRANSPOSE
TREND TRIM TRIMMEAN TRIMRANGE TRUNC TTEST TYPE UNICHAR UNICODE UNIQUE UPPER USDOLLAR VALUE
VALUETOTEXT VAR VAR.P VAR.S VARA VARP VARPA VDB VLOOKUP VSTACK WEBSERVICE WEEKDAY WEEKNUM WEIBULL
WEIBULL.DIST WORKDAY WRAPCOLS WRAPROWS XIRR XLOOKUP XMATCH XNPV XOR YEAR YEARFRAC YIELD YIELDDISC
YIELDMAT Z.TEST ZTEST
`.split(/\s+/).filter(Boolean));

/**
 * What Excel 16's formula parser accepts in a call to each built-in, found by
 * having it take calls with each argument count and a constant in each
 * position: `NAME counts refs`. counts is a comma list of `n`, `n-m` and
 * `n-m/step` (AVERAGEIFS takes 3-255/2, an odd count); refs lists the
 * positions that take only a reference, and `+from/step/offsets` repeats them
 * over a variadic tail, as SUMIFS does for its criteria ranges. LET and LAMBDA
 * are left out: their names and parameters are checked where they are read.
 */
export const FUNCTION_SIGNATURES = `
ABS 1
ACCRINT 6-8
ACCRINTM 4-5
ACOS 1
ACOSH 1
ACOT 1
ACOTH 1
ADDRESS 2-5
AGGREGATE 3-254 +4/1/0
AMORDEGRC 6-7
AMORLINC 6-7
AND 1-255
ARABIC 1
AREAS 1 0
ARRAYTOTEXT 1-2
ASC 1
ASIN 1
ASINH 1
ATAN 1
ATAN2 2
ATANH 1
AVEDEV 1-255
AVERAGE 1-255
AVERAGEA 1-255
AVERAGEIF 2-3 0,2
AVERAGEIFS 3-255/2 0+1/2/0
BAHTTEXT 1
BASE 2-3
BESSELI 2
BESSELJ 2
BESSELK 2
BESSELY 2
BETA.DIST 4-6
BETA.INV 3-5
BETADIST 3-5
BETAINV 3-5
BIN2DEC 1
BIN2HEX 1-2
BIN2OCT 1-2
BINOM.DIST 4
BINOM.DIST.RANGE 3-4
BINOM.INV 3
BINOMDIST 4
BITAND 2
BITLSHIFT 2
BITOR 2
BITRSHIFT 2
BITXOR 2
BYCOL 1-2
BYROW 1-2
CEILING 2
CEILING.MATH 1-3
CEILING.PRECISE 1-2
CELL 1-2 1
CHAR 1
CHIDIST 2
CHIINV 2
CHISQ.DIST 3
CHISQ.DIST.RT 2
CHISQ.INV 2
CHISQ.INV.RT 2
CHISQ.TEST 2
CHITEST 2
CHOOSE 2-255
CHOOSECOLS 2-254
CHOOSEROWS 2-254
CLEAN 1
CODE 1
COLUMN 0-1 0
COLUMNS 1
COMBIN 2
COMBINA 2
COMPLEX 2-3
CONCAT 1-254
CONCATENATE 1-255
CONFIDENCE 3
CONFIDENCE.NORM 3
CONFIDENCE.T 3
CONVERT 3
CORREL 2
COS 1
COSH 1
COT 1
COTH 1
COUNT 1-255
COUNTA 1-255
COUNTBLANK 1 0
COUNTIF 2 0
COUNTIFS 2-254/2 +0/2/0
COUPDAYBS 3-4
COUPDAYS 3-4
COUPDAYSNC 3-4
COUPNCD 3-4
COUPNUM 3-4
COUPPCD 3-4
COVAR 2
COVARIANCE.P 2
COVARIANCE.S 2
CRITBINOM 3
CSC 1
CSCH 1
CUBEKPIMEMBER 3-4
CUBEMEMBER 2-3
CUBEMEMBERPROPERTY 3
CUBERANKEDMEMBER 3-4
CUBESET 2-5
CUBESETCOUNT 1
CUBEVALUE 1-255
CUMIPMT 6
CUMPRINC 6
DATE 3
DATEDIF 3
DATESTRING 1
DATEVALUE 1
DAVERAGE 3 0
DAY 1
DAYS 2
DAYS360 2-3
DB 4-5
DBCS 1
DCOUNT 3 0
DCOUNTA 3 0
DDB 4-5
DEC2BIN 1-2
DEC2HEX 1-2
DEC2OCT 1-2
DECIMAL 2
DEGREES 1
DELTA 1-2
DETECTLANGUAGE 1
DEVSQ 1-255
DGET 3 0
DISC 4-5
DMAX 3 0
DMIN 3 0
DOLLAR 1-2
DOLLARDE 2
DOLLARFR 2
DPRODUCT 3 0
DROP 2-3
DSTDEV 3 0
DSTDEVP 3 0
DSUM 3 0
DURATION 5-6
DVAR 3 0
DVARP 3 0
ECMA.CEILING 2
EDATE 2
EFFECT 2
ENCODEURL 1
EOMONTH 2
ERF 1-2
ERF.PRECISE 1
ERFC 1
ERFC.PRECISE 1
ERROR.TYPE 1
EVEN 1
EXACT 2
EXP 1
EXPAND 2-4
EXPON.DIST 3
EXPONDIST 3
F.DIST 4
F.DIST.RT 3
F.INV 3
F.INV.RT 3
F.TEST 2
FACT 1
FACTDOUBLE 1
FALSE 0
FDIST 3
FIELDVALUE 2
FILTER 2-3
FILTERXML 2
FIND 2-3
FINDB 2-3
FINV 3
FISHER 1
FISHERINV 1
FIXED 1-3
FLOOR 2
FLOOR.MATH 1-3
FLOOR.PRECISE 1-2
FORECAST 3
FORECAST.ETS 3-6
FORECAST.ETS.CONFINT 3-7
FORECAST.ETS.SEASONALITY 2-4
FORECAST.ETS.STAT 3-6
FORECAST.LINEAR 3
FORMULATEXT 1 0
FREQUENCY 2
FTEST 2
FV 3-5
FVSCHEDULE 2
GAMMA 1
GAMMA.DIST 4
GAMMA.INV 3
GAMMADIST 4
GAMMAINV 3
GAMMALN 1
GAMMALN.PRECISE 1
GAUSS 1
GCD 1-255
GEOMEAN 1-255
GESTEP 1-2
GETPIVOTDATA 2-254/2,3
GROUPBY 3-8
GROWTH 1-4
HARMEAN 1-255
HEX2BIN 1-2
HEX2DEC 1
HEX2OCT 1-2
HLOOKUP 3-4
HOUR 1
HSTACK 1-254
HYPERLINK 1-2
HYPGEOM.DIST 5
HYPGEOMDIST 4
IF 2-3
IFERROR 2
IFNA 2
IFS 2-254/2
IMABS 1
IMAGE 1-5
IMAGINARY 1
IMARGUMENT 1
IMCONJUGATE 1
IMCOS 1
IMCOSH 1
IMCOT 1
IMCSC 1
IMCSCH 1
IMDIV 2
IMEXP 1
IMLN 1
IMLOG10 1
IMLOG2 1
IMPORTCSV 1-5
IMPORTTEXT 1-7
IMPOWER 2
IMPRODUCT 1-255
IMREAL 1
IMSEC 1
IMSECH 1
IMSIN 1
IMSINH 1
IMSQRT 1
IMSUB 2
IMSUM 1-255
IMTAN 1
INDEX 2-4
INDIRECT 1-2
INFO 1
INT 1
INTERCEPT 2
INTRATE 4-5
IPMT 4-6
IRR 1-2
ISBLANK 1
ISERR 1
ISERROR 1
ISEVEN 1
ISFORMULA 1 0
ISLOGICAL 1
ISNA 1
ISNONTEXT 1
ISNUMBER 1
ISO.CEILING 1-2
ISODD 1
ISOMITTED 1
ISOWEEKNUM 1
ISPMT 4
ISREF 1
ISTEXT 1
ISTHAIDIGIT 1
KURT 1-255
LARGE 2
LCM 1-255
LEFT 1-2
LEFTB 1-2
LEN 1
LENB 1
LINEST 1-4
LN 1
LOG 1-2
LOG10 1
LOGEST 1-4
LOGINV 3
LOGNORM.DIST 4
LOGNORM.INV 3
LOGNORMDIST 3
LOOKUP 2-3
LOWER 1
MAKEARRAY 3
MAP 2-254
MATCH 2-3
MAX 1-255
MAXA 1-255
MAXIFS 3-253/2 0+1/2/0
MDETERM 1
MDURATION 5-6
MEDIAN 1-255
MID 3
MIDB 3
MIN 1-255
MINA 1-255
MINIFS 3-253/2 0+1/2/0
MINUTE 1
MINVERSE 1
MIRR 3
MMULT 2
MOD 2
MODE 1-255
MODE.MULT 1-254
MODE.SNGL 1-254
MONTH 1
MROUND 2
MULTINOMIAL 1-255
MUNIT 1
N 1
NA 0
NEGBINOM.DIST 4
NEGBINOMDIST 3
NETWORKDAYS 2-3
NETWORKDAYS.INTL 2-4
NOMINAL 2
NORM.DIST 4
NORM.INV 3
NORM.S.DIST 2
NORM.S.INV 1
NORMDIST 4
NORMINV 3
NORMSDIST 1
NORMSINV 1
NOT 1
NOW 0
NPER 3-5
NPV 2-255
NUMBERSTRING 2
NUMBERVALUE 1-3
OCT2BIN 1-2
OCT2DEC 1
OCT2HEX 1-2
ODD 1
ODDFPRICE 8-9
ODDFYIELD 8-9
ODDLPRICE 7-8
ODDLYIELD 7-8
OFFSET 3-5 0
OR 1-255
PDURATION 3
PEARSON 2
PERCENTILE 2
PERCENTILE.EXC 2
PERCENTILE.INC 2
PERCENTOF 2
PERCENTRANK 2-3
PERCENTRANK.EXC 2-3
PERCENTRANK.INC 2-3
PERMUT 2
PERMUTATIONA 2
PHI 1
PHONETIC 1 0
PI 0
PIVOTBY 4-9
PMT 3-5
POISSON 3
POISSON.DIST 3
POWER 2
PPMT 4-6
PRICE 6-7
PRICEDISC 4-5
PRICEMAT 5-6
PROB 3-4
PRODUCT 1-255
PROPER 1
PV 3-5
QUARTILE 2
QUARTILE.EXC 2
QUARTILE.INC 2
QUOTIENT 2
RADIANS 1
RAND 0
RANDARRAY 0-5
RANDBETWEEN 2
RANK 2-3 1
RANK.AVG 2-3 1
RANK.EQ 2-3 1
RATE 3-6
RECEIVED 4-5
REDUCE 3
REGEXEXTRACT 2-4
REGEXREPLACE 3-5
REGEXTEST 2-3
REPLACE 4
REPLACEB 4
REPT 2
RIGHT 1-2
RIGHTB 1-2
ROMAN 1-2
ROUND 2
ROUNDBAHTDOWN 1
ROUNDBAHTUP 1
ROUNDDOWN 2
ROUNDUP 2
ROW 0-1 0
ROWS 1
RRI 3
RSQ 2
RTD 3-255
SCAN 3
SEARCH 2-3
SEARCHB 2-3
SEC 1
SECH 1
SECOND 1
SEQUENCE 1-4
SERIESSUM 4
SHEET 0-1
SHEETS 0-1
SIGN 1
SIN 1
SINGLE 1
SINH 1
SKEW 1-255
SKEW.P 1-254
SLN 3
SLOPE 2
SMALL 2
SORT 1-4
SORTBY 3-253/2,2
SQRT 1
SQRTPI 1
STANDARDIZE 3
STDEV 1-255
STDEV.P 1-254
STDEV.S 1-254
STDEVA 1-255
STDEVP 1-255
STDEVPA 1-255
STEYX 2
STOCKHISTORY 2-254
SUBSTITUTE 3-4
SUBTOTAL 2-255 +1/1/0
SUM 1-255
SUMIF 2-3 0,2
SUMIFS 3-255/2 0+1/2/0
SUMPRODUCT 1-255
SUMSQ 1-255
SUMX2MY2 2
SUMX2PY2 2
SUMXMY2 2
SWITCH 3-254
SYD 4
T 1
T.DIST 3
T.DIST.2T 2
T.DIST.RT 2
T.INV 2
T.INV.2T 2
T.TEST 4
TAKE 2-3
TAN 1
TANH 1
TBILLEQ 3
TBILLPRICE 3
TBILLYIELD 3
TDIST 3
TEXT 2
TEXTAFTER 2-6
TEXTBEFORE 2-6
TEXTJOIN 3-254
TEXTSPLIT 2-6
THAIDAYOFWEEK 1
THAIDIGIT 1
THAIMONTHOFYEAR 1
THAINUMSOUND 1
THAINUMSTRING 1
THAISTRINGLENGTH 1
THAIYEAR 1
TIME 3
TIMEVALUE 1
TINV 2
TOCOL 1-3
TODAY 0
TOROW 1-3
TRANSLATE 1-3
TRANSPOSE 1
TREND 1-4
TRIM 1
TRIMMEAN 2
TRIMRANGE 1-3
TRUE 0
TRUNC 1-2
TTEST 4
TYPE 1
UNICHAR 1
UNICODE 1
UNIQUE 1-3
UPPER 1
USDOLLAR 1-2
VALUE 1
VALUETOTEXT 1-2
VAR 1-255
VAR.P 1-254
VAR.S 1-254
VARA 1-255
VARP 1-255
VARPA 1-255
VDB 5-7
VLOOKUP 3-4
VSTACK 1-254
WEBSERVICE 1
WEEKDAY 1-2
WEEKNUM 1-2
WEIBULL 4
WEIBULL.DIST 4
WORKDAY 2-3
WORKDAY.INTL 2-4
WRAPCOLS 2-3
WRAPROWS 2-3
XIRR 2-3
XLOOKUP 3-6
XMATCH 2-4
XNPV 3
XOR 1-254
YEAR 1
YEARFRAC 2-3
YIELD 6-7
YIELDDISC 4-5
YIELDMAT 5-6
Z.TEST 2-3
ZTEST 2-3
`;

/**
 * Built-ins whose result Excel accepts where a reference is required, as in
 * SUM(INDEX(A2:A9, 3):A9); each was checked as the start of a range.
 */
export const REFERENCE_FUNCTIONS: ReadonlySet<string> = new Set([
	'CHOOSE', 'DROP', 'IF', 'IFS', 'INDEX', 'INDIRECT', 'OFFSET', 'REDUCE', 'SINGLE', 'SWITCH', 'TAKE',
	'TRIMRANGE', 'XLOOKUP',
]);

/**
 * Names Excel will not call from a cell: macro-sheet commands such as
 * GET.CELL, and SPLIT. Any other unknown name is taken as a user-defined
 * function. Found by having Excel take a call to every name in EXCEL.EXE;
 * a file holding a call to one of these does not open.
 */
export const RESERVED_FUNCTIONS: ReadonlySet<string> = new Set(`
A1.R1C1 ABSREF ACTIVE.CELL ADD.BAR ADD.COMMAND ADD.MENU ADD.TOOLBAR APP.TITLE ARGUMENT AXES BEEP
BREAK CALL CALLER CANCEL.KEY CHECK.COMMAND CMD_FORMULA.REPLACE2 COPY CREATE.OBJECT CUSTOM.REPEAT
CUSTOM.UNDO CUT DELETE.BAR DELETE.COMMAND DELETE.MENU DELETE.TOOLBAR DEREF DIALOG.BOX DIRECTORY
DOCUMENTS ECHO ELSE ELSE.IF ENABLE.COMMAND ENABLE.TOOL END.IF ERROR EVALUATE EXEC EXECUTE FCLOSE
FILES FONT FOPEN FOR FOR.CELL FORMULA FORMULA.CONVERT FPOS FREAD FREADLN FSIZE FWRITE FWRITELN
GET.BAR GET.CELL GET.CHART.ITEM GET.DEF GET.DOCUMENT GET.FORMULA GET.LINK.INFO GET.MOVIE GET.NAME
GET.NOTE GET.OBJECT GET.PIVOT.FIELD GET.PIVOT.ITEM GET.PIVOT.TABLE GET.TOOL GET.TOOLBAR GET.WINDOW
GET.WORKBOOK GET.WORKSPACE GOTO GROUP HALT HELP HIDE INITIATE INPUT INSERT.OBJECT LAST.ERROR LINKS
MOVE MOVIE.COMMAND NAMES NEXT NOTE OPEN.DIALOG OPTIONS.LISTS.GET OUTLINE PAUSE PIVOT.ADD.DATA POKE
PRESS.TOOL QUIT REFTEXT REGISTER REGISTER.ID RELREF RENAME.COMMAND REQUEST RESET.TOOLBAR RESTART
RESULT RESUME RETURN RUN SAVE.DIALOG SAVE.TOOLBAR SCENARIO.GET SELECT SELECTION SEND.KEYS SERIES
SET.NAME SET.VALUE SHOW.BAR SIZE SPELLING.CHECK SPLIT STEP STYLE TABLE TERMINATE TEXT.BOX TEXTREF
UNDO UNREGISTER VIEW.GET VOLATILE WAIT WHILE WINDOW.TITLE WINDOWS ZOOM
`.split(/\s+/).filter(Boolean));
