#!/usr/bin/env python
"""Writes the type names each standard library a VBA project references holds.

    python scripts/dump-library-type-names.py

A name in an As clause that no type of the project and no type of any
referenced library spells is the VBE compile error "User-defined type not
defined" (issue #234, measured in Excel 16.0: `Private Function F() As
Qwerty`). The analyzer can say so only where it knows every name each
referenced library holds, so this reads them all, hidden and restricted
ones included, from the registered type libraries, and writes them to
src/analyzer/host/libraryTypeNames.ts, which is committed: CI needs
neither Office nor pywin32.

Requires Windows, Office and pywin32.
"""
import os

import pythoncom

OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'analyzer', 'host', 'libraryTypeNames.ts')

# The library name a project's references record, and its type library.
LIBS = {
    'VBA': '{000204EF-0000-0000-C000-000000000046}',
    'Excel': '{00020813-0000-0000-C000-000000000046}',
    'Word': '{00020905-0000-0000-C000-000000000046}',
    'PowerPoint': '{91493440-5A91-11CF-8700-00AA0060263B}',
    'Access': '{4AFFC9A0-5F99-101B-AF4E-00AA003F0F07}',
    'Office': '{2DF8D04C-5BFA-101B-BDE5-00AA0044DE52}',
    'stdole': '{00020430-0000-0000-C000-000000000046}',
    'MSForms': '{0D452EE1-E08F-101A-852E-02608C4D0BB4}',
}


def load(guid):
    """The newest registered version of the type library."""
    for major in range(20, 0, -1):
        for minor in range(30, -1, -1):
            try:
                return pythoncom.LoadRegTypeLib(guid, major, minor), (major, minor)
            except pythoncom.com_error:
                continue
    raise SystemExit(f'{guid} is not registered')


lines = [
    '// Generated by scripts/dump-library-type-names.py from the registered type',
    '// libraries: every type name each library holds, hidden and restricted',
    '// ones included, lowercased and space-separated (issue #234).',
    '',
    'const NAMES: Readonly<Record<string, string>> = {',
]
for name, guid in LIBS.items():
    lib, version = load(guid)
    names = sorted({lib.GetDocumentation(i)[0].lower() for i in range(lib.GetTypeInfoCount())})
    assert all(n.isascii() for n in names), name
    lines.append(f'\t// {lib.GetDocumentation(-1)[0]} {version[0]}.{version[1]}, {len(names)} types.')
    lines.append(f"\t{name.lower()}: '{' '.join(names)}',")
lines += [
    '};',
    '',
    '/** The type names of a library by the name a project reference records, lowercased; undefined for a library not read. */',
    'export function libraryTypeNames(library: string): ReadonlySet<string> | undefined {',
    '\tconst key = library.toLowerCase();',
    '\tif (!Object.hasOwn(NAMES, key)) { return undefined; }',
    '\treturn CACHE[key] ??= new Set(NAMES[key].split(\' \'));',
    '}',
    '',
    'const CACHE: Record<string, Set<string>> = {};',
    '',
]
with open(OUT, 'w', encoding='ascii', newline='\n') as f:
    f.write('\n'.join(lines))
print('wrote', OUT)
