#!/usr/bin/env python3
"""Generate reference JSON using pinned pyVBAReference plus COM identities.

Windows + pywin32 required. Pass a clean pyVBAReference checkout at the pin:
    python scripts/dump-scripting-typelibs.py path/to/pyVBAReference
    node scripts/generate-host-object-model.mjs scripting
    node scripts/generate-host-object-model.mjs regexp
No Office application is started and no project references are changed.
"""
import json
from pathlib import Path
import runpy
import subprocess
import sys
import tempfile
import pythoncom

ROOT = Path(__file__).resolve().parent.parent
SOURCE_REVISION = 'a6c39d0617085297e88bec7de0ee8afb7aa0746b'
if len(sys.argv) != 2:
    raise SystemExit('Pass a clean pyVBAReference checkout at ' + SOURCE_REVISION)
source = Path(sys.argv[1]).resolve()
revision = subprocess.check_output(['git', '-C', str(source), 'rev-parse', 'HEAD'], text=True).strip()
if revision != SOURCE_REVISION:
    raise SystemExit('Expected pyVBAReference revision ' + SOURCE_REVISION)
subprocess.run(['git', '-C', str(source), 'diff', '--exit-code', 'HEAD', '--',
                'scrape_excel_object_model.py', 'consolidate_reference.py', 'mslearn_docs.py'], check=True)
sys.path.insert(0, str(source))
scraper = runpy.run_path(str(source / 'scrape_excel_object_model.py'))
LIBRARIES = [
    ('scripting', '{420B2830-E718-11CF-893D-00A0C9054228}', 1, 0),
    ('regexp', '{3F4DACA7-160D-11D2-A8E9-00104B365C9F}', 5, 5),
]
for token, guid, major, minor in LIBRARIES:
    tlb = pythoncom.LoadRegTypeLib(guid, major, minor)
    name, description = tlb.GetDocumentation(-1)[:2]
    out = ROOT / 'reference' / token / 'json'
    out.mkdir(parents=True, exist_ok=True)
    # These two libraries have no Office VBA-API prose corpus; the COM help
    # strings and signatures are exactly those pyVBAReference extracts.
    with tempfile.TemporaryDirectory(prefix='xlide-reference-') as temp:
        written = scraper['scrape_typelib'](tlb, description or name, temp)
        for path in (Path(temp) / 'json').glob('*.json'):
            (out / path.name).write_bytes(path.read_bytes())
    provenance = f'{name} {major}.{minor} via pyVBAReference {SOURCE_REVISION}'
    type_names = []
    for i in range(tlb.GetTypeInfoCount()):
        info = tlb.GetTypeInfo(i)
        type_name = info.GetDocumentation(-1)[0]
        type_names.append(type_name.lower())
        if info.GetTypeAttr().typekind != pythoncom.TKIND_COCLASS:
            continue
        default, _ = scraper['resolve_coclass_interfaces'](info)
        path = out / (type_name + '.json')
        if default is not None and path.exists():
            entry = json.loads(path.read_text(encoding='utf-8'))
            entry['defaultInterface'] = default.GetDocumentation(-1)[0]
            path.write_text(json.dumps(entry, indent=2) + '\n', encoding='utf-8')
    for path in out.glob('*.json'):
        entry = json.loads(path.read_text(encoding='utf-8'))
        entry['source'] = provenance
        if path.name == '_index.json':
            entry.update(guid=guid, version=f'{major}.{minor}', name=name,
                         sourceRevision=SOURCE_REVISION, typeNames=sorted(set(type_names)))
        path.write_text(json.dumps(entry, indent=2) + '\n', encoding='utf-8')
    print(f'{name}: {written} types generated by pyVBAReference')
