#!/usr/bin/env python
"""Writes the names of Word's built-in styles.

    python scripts/dump-word-builtin-styles.py

Styles.Add refuses a built-in style's name, in any case, with 5173 (issue
#610, measured in Word 16.0: "Normal", "normal", "Heading 1", and 20
names drawn at random from this list). The names are read from the
styles a new document marks BuiltIn, in a private Word instance, and
written to src/analyzer/host/wordBuiltinStyles.ts, which is committed:
CI needs neither Office nor pywin32. They are the names of Word's English
interface.

Requires Windows, Word and pywin32.
"""
import os

import win32com.client

OUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'analyzer', 'host', 'wordBuiltinStyles.ts')

word = win32com.client.gencache.EnsureDispatch(win32com.client.DispatchEx('Word.Application'))
word.Visible = False
try:
    doc = word.Documents.Add()
    names = set()
    for style in doc.Styles:
        try:
            if style.BuiltIn:
                names.add(style.NameLocal)
        except Exception:  # a style the collection lists but cannot describe
            continue
    doc.Close(False)
    build = word.Build
finally:
    word.Quit(False)

ordered = sorted(names, key=str.lower)
assert all(name.isascii() for name in ordered), 'a non-ASCII style name: check the Word language'
lines = [
    '// Generated by scripts/dump-word-builtin-styles.py from Word ' + build + '. Do not edit.',
    '//',
    "// The names of Word's built-in styles, in its English interface, lower",
    '// case: Styles.Add refuses each, in any case (issue #610).',
    '',
    'export const WORD_BUILTIN_STYLES: ReadonlySet<string> = new Set([',
]
lines += [f'\t{name.lower()!r},' for name in ordered]
lines += [']);', '']
with open(OUT, 'w', encoding='utf-8', newline='\n') as handle:
    handle.write('\n'.join(lines))
print(len(ordered), 'names from Word', build)
