#!/usr/bin/env python
"""Writes each Office type's default member (DISPID 0) from its type library.

    python scripts/dump-default-members.py

A Word Range's default member is Text, a named property the library gives
DISPID 0 (DISPID_VALUE), so `rng = "x"` and `s = rng` read and write the
text (issue #438, measured in Word 16.0). The reference dumps the host
models are generated from carry no DISPIDs, and the Excel model names its
defaults `_Default` by hand. This reads the installed Word, PowerPoint,
Access and DAO libraries and writes src/analyzer/host/hostDefaultMembers.ts,
which is committed: CI needs neither Office nor pywin32.

Requires Windows, Office and pywin32.
"""
import os

import pythoncom

OFFICE = 'C:/Program Files/Microsoft Office/root/Office16'
SHARED = 'C:/Program Files/Microsoft Office/root/VFS/ProgramFilesCommonX64/Microsoft Shared/OFFICE16'
LIBRARIES = [
    ('Word', OFFICE, 'MSWORD.OLB'),
    ('PowerPoint', OFFICE, 'MSPPT.OLB'),
    ('Access', OFFICE, 'MSACC.OLB'),
    # DAO, which every new Access database references (issue #464).
    ('DAO', SHARED, 'ACEDAO.DLL'),
]
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'analyzer', 'host', 'hostDefaultMembers.ts')

TKIND_INTERFACE = 3
TKIND_DISPATCH = 4
INVOKE_PROPERTYGET = 2
INVOKE_PROPERTYPUT = 4
INVOKE_PROPERTYPUTREF = 8
PARAMFLAG_FOPT = 0x10
PARAMFLAG_FHASDEFAULT = 0x20
VT_PTR = 26
VT_USERDEFINED = 29
VT_NAMES = {
    2: 'Integer', 3: 'Long', 4: 'Single', 5: 'Double', 6: 'Currency', 7: 'Date',
    8: 'String', 9: 'Object', 11: 'Boolean', 12: 'Variant', 13: 'Object',
    16: 'Byte', 17: 'Byte', 18: 'Integer', 19: 'Long', 20: 'LongLong', 21: 'LongLong',
    22: 'Long', 23: 'Long', 24: 'void', 25: 'void',
}


def type_name(info, typedesc, prefix):
    """The VBA name of a return type: a library type as `Word.Range`."""
    if isinstance(typedesc, int):
        return VT_NAMES.get(typedesc, 'Variant')
    vt, inner = typedesc
    if vt == VT_PTR:
        return type_name(info, inner, prefix)
    if vt == VT_USERDEFINED:
        try:
            ref = info.GetRefTypeInfo(inner)
            name = ref.GetDocumentation(-1)[0]
            library = ref.GetContainingTypeLib()[0].GetDocumentation(-1)[0]
        except pythoncom.com_error:
            return 'Variant'
        name = name[1:] if name.startswith('_') else name
        return f'{prefix}.{name}' if library == prefix else f'{library}.{name}'
    return VT_NAMES.get(vt, 'Variant')


def defaults(prefix, path):
    tlb = pythoncom.LoadTypeLib(path)
    out = {}
    for index in range(tlb.GetTypeInfoCount()):
        try:
            info = tlb.GetTypeInfo(index)
            attr = info.GetTypeAttr()
            name = tlb.GetDocumentation(index)[0]
        except pythoncom.com_error:
            continue
        if attr.typekind not in (TKIND_INTERFACE, TKIND_DISPATCH):
            continue
        key = f"{prefix}.{name[1:] if name.startswith('_') else name}"
        descs = []
        for i in range(attr.cFuncs):
            try:
                descs.append(info.GetFuncDesc(i))
            except pythoncom.com_error:
                continue
        writable = any(desc.memid == 0 and desc.invkind in (INVOKE_PROPERTYPUT, INVOKE_PROPERTYPUTREF) for desc in descs)
        for desc in descs:
            if desc.memid != 0 or desc.invkind not in (1, INVOKE_PROPERTYGET):
                continue
            member = info.GetNames(desc.memid)[0]
            required = sum(1 for arg in desc.args if not arg[1] & (PARAMFLAG_FOPT | PARAMFLAG_FHASDEFAULT))
            out.setdefault(key, {
                'name': member,
                'kind': 'property' if desc.invkind == INVOKE_PROPERTYGET else 'method',
                'required': required,
                'params': len(desc.args),
                'returns': type_name(info, desc.rettype[0], prefix),
                'writable': writable,
            })
    return out


def main():
    lines = [
        '// Generated by scripts/dump-default-members.py from the installed Word,',
        '// PowerPoint, Access and DAO type libraries. Do not hand-edit: regenerate',
        '// instead.',
        '//',
        "// Each type's default member, the one the library gives DISPID 0: a Word",
        "// Range's is Text, so `rng = \"x\"` writes the text and `s = rng` reads it",
        '// (issue #438). `required` counts the parameters a call must pass,',
        '// `params` all it takes; `writable` is whether a Let or Set reaches it.',
        '',
        'export interface HostDefaultMember {',
        '\tname: string;',
        "\tkind: 'property' | 'method';",
        '\trequired: number;',
        '\tparams: number;',
        '\treturns: string;',
        '\twritable: boolean;',
        '}',
        '',
        'export const HOST_DEFAULT_MEMBERS: Readonly<Record<string, HostDefaultMember>> = {',
    ]
    found = {}
    for prefix, folder, file in LIBRARIES:
        found.update(defaults(prefix, os.path.join(folder, file)))
    for key in sorted(found):
        d = found[key]
        lines.append(f"\t'{key}': {{ name: '{d['name']}', kind: '{d['kind']}', required: {d['required']}, params: {d['params']}, returns: '{d['returns']}', writable: {'true' if d['writable'] else 'false'} }},")
    lines.append('};')
    with open(OUT, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write('\n'.join(lines) + '\n')
    print(f'{OUT}: {len(found)} default members')


if __name__ == '__main__':
    main()
