"""Writes src/analyzer/host/msFormsFormControlMembers.ts: the members the VBE
binds a form's control against while compiling, for the control classes it
checks there (issue #226).

    python scripts/generate-msforms-form-control-members.py

Reads the registered Microsoft Forms 2.0 type library (FM20.DLL) with
LoadRegTypeLib: each class's default interface and the IControl extender,
hidden members included, IUnknown and IDispatch left out. The reference
dump the completion lists come from omits hidden members such as BoundValue
and FontBold, which compile, so it cannot prove a member absent.

Which classes the VBE checks was measured in 64-bit Excel 16.0 (build 20326,
2026-09-30): `f.T1.Nope` on a form's TextBox, ListBox, CheckBox,
CommandButton, Label, ComboBox, SpinButton, ScrollBar or Image is "Method or
data member not found"; on a Frame, OptionButton, ToggleButton, MultiPage or
TabStrip it compiles.
"""
from pathlib import Path

import pythoncom

MSFORMS = '{0D452EE1-E08F-101A-852E-02608C4D0BB4}'
CHECKED = ['CheckBox', 'ComboBox', 'CommandButton', 'Image', 'Label', 'ListBox', 'ScrollBar', 'SpinButton', 'TextBox']
PLUMBING = {'AddRef', 'Release', 'QueryInterface', 'GetIDsOfNames', 'GetTypeInfo', 'GetTypeInfoCount', 'Invoke'}
OUT = Path(__file__).resolve().parent.parent / 'src' / 'analyzer' / 'host' / 'msFormsFormControlMembers.ts'


def members_of(info):
    attr = info.GetTypeAttr()
    if attr.typekind == pythoncom.TKIND_INTERFACE and attr.wTypeFlags & pythoncom.TYPEFLAG_FDUAL:
        try:
            info = info.GetRefTypeInfo(info.GetRefTypeOfImplType(-1))
            attr = info.GetTypeAttr()
        except pythoncom.com_error:
            pass
    names = set()
    for i in range(attr.cFuncs):
        names.add(info.GetNames(info.GetFuncDesc(i).memid)[0])
    for i in range(attr.cVars):
        names.add(info.GetNames(info.GetVarDesc(i).memid)[0])
    return names - PLUMBING


def default_interface(info):
    attr = info.GetTypeAttr()
    for impl in range(attr.cImplTypes):
        flags = info.GetImplTypeFlags(impl)
        if flags & 1 and not flags & 2:
            return info.GetRefTypeInfo(info.GetRefTypeOfImplType(impl))
    return None


def main():
    lib = pythoncom.LoadRegTypeLib(MSFORMS, 2, 0, 0)
    classes = {}
    extender = set()
    for index in range(lib.GetTypeInfoCount()):
        name = lib.GetDocumentation(index)[0]
        info = lib.GetTypeInfo(index)
        if name == 'IControl':
            extender = members_of(info)
        elif name in CHECKED and info.GetTypeAttr().typekind == pythoncom.TKIND_COCLASS:
            classes[name] = members_of(default_interface(info))
    lines = [
        '// Generated by scripts/generate-msforms-form-control-members.py from the',
        '// registered Microsoft Forms 2.0 type library. Do not edit by hand.',
        '//',
        "// The members the VBE binds a form's control against while compiling, for",
        '// the classes it checks there (issue #226): the default interface and the',
        '// IControl extender, hidden members included.',
        '',
        'export const MSFORMS_FORM_CONTROL_MEMBERS: Readonly<Record<string, readonly string[]>> = {',
    ]
    for name in CHECKED:
        members = sorted(classes[name] | extender, key=str.lower)
        lines.append(f"\t'MSForms.{name}': [")
        row = '\t\t'
        for member in members:
            item = f"'{member}', "
            if len(row) + len(item) > 100:
                lines.append(row.rstrip())
                row = '\t\t'
            row += item
        lines.append(row.rstrip())
        lines.append('\t],')
    lines.append('};')
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
    print(f'wrote {OUT}')


if __name__ == '__main__':
    main()
