// Generated from the VBA language reference. Do not hand-edit.
// Regenerate with `node scripts/generate-vba-runtime-docs.mjs`.
//
// One-line summaries for the built-in VBA functions and statements, taken
// verbatim from the first prose paragraph of each page under
// learn.microsoft.com/office/vba/language/reference/user-interface-help
// (via the MicrosoftDocs/VBA-Docs source), so hover, completion and the call
// tip describe what a built-in DOES rather than only how it is spelled
// (issue #41).
//
// Two exceptions, both stated rather than invented: the type-conversion
// functions share one reference page and take their line from that page's
// own return-type table, and CVDate is described from the compatibility
// paragraph that page devotes to it.
//
// Names with no entry are the hidden and byte-variant built-ins (VarPtr,
// LenB, MidB, ...), which the reference documents only in passing on their
// parent page; they keep their signature and gain no invented prose.

/** Canonical built-in name -> its one-line reference summary. */
export const VBA_RUNTIME_DESCRIPTIONS: Readonly<Record<string, string>> = {
	"Abs": "Returns a value of the same type that is passed to it specifying the absolute value of a number.",
	"AppActivate": "Activates an application window.",
	"Array": "Returns a Variant containing an array.",
	"Asc": "Returns an Integer representing the character code corresponding to the first letter in a string.",
	"Atn": "Returns a Double specifying the arctangent of a number.",
	"Beep": "Sounds a tone through the computer's speaker.",
	"CallByName": "Executes a method of an object, or sets or returns a property of an object.",
	"CBool": "Coerces an expression to the Boolean data type.",
	"CByte": "Coerces an expression to the Byte data type.",
	"CCur": "Coerces an expression to the Currency data type.",
	"CDate": "Coerces an expression to the Date data type.",
	"CDbl": "Coerces an expression to the Double data type.",
	"CDec": "Coerces an expression to the Decimal data type.",
	"ChDir": "Changes the current directory or folder.",
	"ChDrive": "Changes the current drive.",
	"Choose": "Selects and returns a value from a list of arguments.",
	"Chr": "Returns a String containing the character associated with the specified character code.",
	"CInt": "Coerces an expression to the Integer data type.",
	"CLng": "Coerces an expression to the Long data type.",
	"CLngLng": "Coerces an expression to the LongLong data type.",
	"CLngPtr": "Coerces an expression to the LongPtr data type.",
	"Command": "Returns the argument portion of the command line used to launch Microsoft Visual Basic or an executable program developed with Visual Basic. The Visual Basic Command function is available in Microsoft Access, but not in other Microsoft Office applications.",
	"Cos": "Returns a Double specifying the cosine of an angle.",
	"CreateObject": "Creates and returns a reference to an ActiveX object.",
	"CSng": "Coerces an expression to the Single data type.",
	"CStr": "Coerces an expression to the String data type.",
	"CurDir": "Returns a Variant (String) representing the current path.",
	"CVar": "Coerces an expression to the Variant data type.",
	"CVDate": "Coerces an expression to the Date data type, returning a Variant whose subtype is Date; provided for compatibility with previous versions of Visual Basic.",
	"CVErr": "Returns a Variant of subtype Error containing an error number specified by the user.",
	"Date": "Returns a Variant (Date) containing the current system date.",
	"DateAdd": "Returns a Variant (Date) containing a date to which a specified time interval has been added.",
	"DateDiff": "Returns a Variant (Long) specifying the number of time intervals between two specified dates.",
	"DatePart": "Returns a Variant (Integer) containing the specified part of a given date.",
	"DateSerial": "Returns a Variant (Date) for a specified year, month, and day.",
	"DateValue": "Returns a Variant (Date).",
	"Day": "Returns a Variant (Integer) specifying a whole number between 1 and 31, inclusive, representing the day of the month.",
	"DDB": "Returns a Double specifying the depreciation of an asset for a specific time period by using the double-declining balance method or some other method you specify.",
	"DeleteSetting": "Deletes a section or key setting from an application's entry in the Windows registry or (on the Macintosh) information in the application's initialization file.",
	"Dir": "Returns a String representing the name of a file, directory, or folder that matches a specified pattern or file attribute, or the volume label of a drive.",
	"DoEvents": "Yields execution so that the operating system can process other events.",
	"Environ": "Returns the String associated with an operating system environment variable. Not available on the Macintosh.",
	"EOF": "Returns an Integer containing the Boolean value True when the end of a file opened for Random or sequential Input has been reached.",
	"Error": "Returns the error message that corresponds to a given error number.",
	"Exp": "Returns a Double specifying _e_ (the base of natural logarithms) raised to a power.",
	"FileAttr": "Returns a Long representing the file mode for files opened by using the Open statement.",
	"FileCopy": "Copies a file.",
	"FileDateTime": "Returns a Variant (Date) that indicates the date and time when a file was created or last modified.",
	"FileLen": "Returns a Long specifying the length of a file in bytes.",
	"Filter": "Returns a zero-based array containing a subset of a string array based on a specified filter criteria.",
	"Fix": "Returns the integer portion of a number.",
	"Format": "Returns a Variant (String) containing an expression formatted according to instructions contained in a format expression.",
	"FormatCurrency": "Returns an expression formatted as a currency value by using the currency symbol defined in the system control panel.",
	"FormatDateTime": "Returns an expression formatted as a date or time.",
	"FormatNumber": "Returns an expression formatted as a number.",
	"FormatPercent": "Returns an expression formatted as a percentage (multipled by 100) with a trailing % character.",
	"FreeFile": "Returns an Integer representing the next file number available for use by the Open statement.",
	"FV": "Returns a Double specifying the future value of an annuity based on periodic fixed payments and a fixed interest rate.",
	"GetAllSettings": "Returns a list of key settings and their respective values (originally created with SaveSetting) from an application's entry in the Windows registry or (on the Macintosh) information in the application's initialization file.",
	"GetAttr": "Returns an Integer representing the attributes of a file, directory, or folder.",
	"GetObject": "Returns a reference to an object provided by an ActiveX component.",
	"GetSetting": "Returns a key setting value from an application's entry in the Windows registry or (on the Macintosh) information in the application's initialization file.",
	"Hex": "Returns a String representing the hexadecimal value of a number.",
	"Hour": "Returns a Variant (Integer) specifying a whole number between 0 and 23, inclusive, representing the hour of the day.",
	"IIf": "Returns one of two parts, depending on the evaluation of an expression.",
	"IMEStatus": "Returns an Integer specifying the current Input Method Editor (IME) mode of Microsoft Windows; available in East Asian versions only.",
	"Input": "Returns String containing characters from a file opened in Input or Binary mode.",
	"InputBox": "Displays a prompt in a dialog box, waits for the user to input text or click a button, and returns a String containing the contents of the text box.",
	"InStr": "Returns a Variant (Long) specifying the position of the first occurrence of one string within another.",
	"InStrRev": "Returns the position of an occurrence of one string within another, from the end of the string.",
	"Int": "Returns the integer portion of a number.",
	"IPmt": "Returns a Double specifying the interest payment for a given period of an annuity based on periodic, fixed payments and a fixed interest rate.",
	"IRR": "Returns a Double specifying the internal rate of return for a series of periodic cash flows (payments and receipts).",
	"IsArray": "Returns a Boolean value indicating whether a variable is an array.",
	"IsDate": "Returns True if the expression is a date or is recognizable as a valid date or time; otherwise, it returns False.",
	"IsEmpty": "Returns a Boolean value indicating whether a variable has been initialized.",
	"IsError": "Returns a Boolean value indicating whether an expression is an error value.",
	"IsMissing": "Returns a Boolean value indicating whether an optional Variant argument has been passed to a procedure.",
	"IsNull": "Returns a Boolean value that indicates whether an expression contains no valid data (Null).",
	"IsNumeric": "Returns a Boolean value indicating whether an expression can be evaluated as a number.",
	"IsObject": "Returns a Boolean value indicating whether an identifier represents an object variable.",
	"Join": "Returns a string created by joining a number of substrings contained in an array.",
	"Kill": "Deletes files from a disk.",
	"LBound": "Returns a Long containing the smallest available subscript for the indicated dimension of an array.",
	"LCase": "Returns a String that has been converted to lowercase.",
	"Left": "Returns a Variant (String) containing a specified number of characters from the left side of a string.",
	"Left$": "Returns a Variant (String) containing a specified number of characters from the left side of a string.",
	"Len": "Returns a Long containing the number of characters in a string or the number of bytes required to store a variable.",
	"Line": "Reads a single line from an open sequential file and assigns it to a String variable.",
	"Load": "Loads an object but doesn't show it.",
	"Loc": "Returns a Long specifying the current read/write position within an open file.",
	"LOF": "Returns a Long representing the size, in bytes, of a file opened by using the Open statement.",
	"Log": "Returns a Double specifying the natural logarithm of a number.",
	"LTrim": "Returns a Variant (String) containing a copy of a specified string without leading spaces (LTrim), trailing spaces (RTrim), or both leading and trailing spaces (Trim).",
	"MacID": "Used on the Macintosh to convert a 4-character constant to a value that may be used by Dir, Kill, Shell, and AppActivate.",
	"MacScript": "Executes an AppleScript script and returns a value returned by the script, if any.",
	"Mid": "Returns a Variant (String) containing a specified number of characters from a string.",
	"Mid$": "Returns a Variant (String) containing a specified number of characters from a string.",
	"Minute": "Returns a Variant (Integer) specifying a whole number between 0 and 59, inclusive, representing the minute of the hour.",
	"MIRR": "Returns a Double specifying the modified internal rate of return for a series of periodic cash flows (payments and receipts).",
	"MkDir": "Creates a new directory or folder.",
	"Month": "Returns a Variant (Integer) specifying a whole number between 1 and 12, inclusive, representing the month of the year.",
	"MonthName": "Returns a string indicating the specified month.",
	"MsgBox": "Displays a message in a dialog box, waits for the user to click a button, and returns an Integer indicating which button the user clicked.",
	"Name": "Renames a disk file, directory, or folder.",
	"Now": "Returns a Variant (Date) specifying the current date and time according to your computer's system date and time.",
	"NPer": "Returns a Double specifying the number of periods for an annuity based on periodic, fixed payments and a fixed interest rate.",
	"NPV": "Returns a Double specifying the net present value of an investment based on a series of periodic cash flows (payments and receipts) and a discount rate.",
	"Oct": "Returns a Variant (String) representing the octal value of a number.",
	"Partition": "Returns a Variant (String) indicating where a number occurs within a calculated series of ranges.",
	"Pmt": "Returns a Double specifying the payment for an annuity based on periodic, fixed payments and a fixed interest rate.",
	"PPmt": "Returns a Double specifying the principal payment for a given period of an annuity based on periodic, fixed payments and a fixed interest rate.",
	"PV": "Returns a Double specifying the present value of an annuity based on periodic, fixed payments to be paid in the future and a fixed interest rate.",
	"QBColor": "Returns a Long representing the RGB color code corresponding to the specified color number.",
	"Randomize": "Initializes the random-number generator.",
	"Rate": "Returns a Double specifying the interest rate per period for an annuity.",
	"Replace": "Returns a string, which is a substring of a string expression beginning at the start position (defaults to 1), in which a specified substring has been replaced with another substring a specified number of times.",
	"Replace$": "Returns a string, which is a substring of a string expression beginning at the start position (defaults to 1), in which a specified substring has been replaced with another substring a specified number of times.",
	"Reset": "Closes all disk files opened by using the Open statement.",
	"RGB": "Returns a Long whole number representing an RGB color value.",
	"Right": "Returns a Variant (String) containing a specified number of characters from the right side of a string.",
	"Right$": "Returns a Variant (String) containing a specified number of characters from the right side of a string.",
	"RmDir": "Removes an existing directory or folder.",
	"Rnd": "Returns a Single containing a pseudo-random number.",
	"Round": "Returns a number rounded to a specified number of decimal places.",
	"RTrim": "Returns a Variant (String) containing a copy of a specified string without leading spaces (LTrim), trailing spaces (RTrim), or both leading and trailing spaces (Trim).",
	"SaveSetting": "Saves or creates an application entry in the application's entry in the Windows registry or (on the Macintosh) information in the application's initialization file.",
	"Second": "Returns a Variant (Integer) specifying a whole number between 0 and 59, inclusive, representing the second of the minute.",
	"Seek": "Returns a Long specifying the current read/write position within a file opened by using the Open statement.",
	"SendKeys": "Sends one or more keystrokes to the active window as if typed at the keyboard.",
	"SetAttr": "Sets attribute information for a file.",
	"Sgn": "Returns a Variant (Integer) indicating the sign of a number.",
	"Shell": "Runs an executable program and returns a Variant (Double) representing the program's task ID if successful; otherwise, it returns zero.",
	"Sin": "Returns a Double specifying the sine of an angle.",
	"SLN": "Returns a Double specifying the straight-line depreciation of an asset for a single period.",
	"Space": "Returns a Variant (String) consisting of the specified number of spaces.",
	"Space$": "Returns a Variant (String) consisting of the specified number of spaces.",
	"Spc": "Used with the Print # statement or the Print method to position output.",
	"Split": "Returns a zero-based, one-dimensional array containing a specified number of substrings.",
	"Sqr": "Returns a Double specifying the square root of a number.",
	"Str": "Returns a Variant (String) representation of a number.",
	"StrComp": "Returns a Variant (Integer) indicating the result of a string comparison.",
	"StrConv": "Returns a Variant (String) converted as specified.",
	"String": "Returns a Variant (String) containing a repeating character string of the length specified.",
	"String$": "Returns a Variant (String) containing a repeating character string of the length specified.",
	"StrReverse": "Returns a string in which the character order of a specified string is reversed.",
	"Switch": "Evaluates a list of expressions and returns a Variant value or an expression associated with the first expression in the list that is True.",
	"SYD": "Returns a Double specifying the sum-of-years' digits depreciation of an asset for a specified period.",
	"Tab": "Used with the Print # statement or the Print method to position output.",
	"Tan": "Returns a Double specifying the tangent of an angle.",
	"Time": "Returns a Variant (Date) indicating the current system time.",
	"Timer": "Returns a Single representing the number of seconds elapsed since midnight.",
	"TimeSerial": "Returns a Variant (Date) containing the time for a specific hour, minute, and second.",
	"TimeValue": "Returns a Variant (Date) containing the time.",
	"Trim": "Returns a Variant (String) containing a copy of a specified string without leading spaces (LTrim), trailing spaces (RTrim), or both leading and trailing spaces (Trim).",
	"TypeName": "Returns a String that provides information about a variable.",
	"UBound": "Returns a Long data type containing the largest available subscript for the indicated dimension of an array.",
	"UCase": "Returns a Variant (String) containing the specified string, converted to uppercase.",
	"Unload": "Removes an object from memory.",
	"Val": "Returns the numbers contained in a string as a numeric value of appropriate type.",
	"VarType": "Returns an Integer indicating the subtype of a variable, or the type of an object's default property.",
	"Weekday": "Returns a Variant (Integer) containing a whole number representing the day of the week.",
	"WeekdayName": "Returns a string indicating the specified day of the week.",
	"Width": "Assigns an output line width to a file opened by using the Open statement.",
	"Year": "Returns a Variant (Integer) containing a whole number representing the year.",
};

/** Lowercased name -> summary, for the case-insensitive lookup VBA needs. */
const BY_LOWER_NAME: ReadonlyMap<string, string> = new Map(
	Object.entries(VBA_RUNTIME_DESCRIPTIONS).map(([name, text]) => [name.toLowerCase(), text]),
);

/** The reference summary for a built-in, or undefined when none is documented. */
export function vbaRuntimeDescription(name: string): string | undefined {
	return BY_LOWER_NAME.get(name.toLowerCase());
}
