// What an AI agent needs to know to work with XLIDE. The sidebar's Agent
// Instructions dialog shows it for the user to copy into their agent's
// instructions file. An agent reaches a file's VBA through the language model
// tools, which GitHub Copilot calls, or, for an agent that is not Copilot,
// through the owner's recommended route of Python plus pyOpenVBA,
// pyvbaanalysis and pyvbaharness, installed only with the user's word. Failing
// that, through the xlide-vba: documents if its edits go through VS Code's
// editor APIs, or through an export. A module has
// no path on disk: measured in VS Code, a tool addressing it by path gets
// ENOENT, and the Claude Code extension's IDE calls build file: URIs only, so
// the text says that before an agent tries the path and mistakes an exported
// copy for the module. A test keeps it naming every tool in package.json, and
// no tool, command or button that is not there.

/** What the user does with the instructions, one step each. Backticks mark file names. */
export const AGENT_INSTRUCTIONS_STEPS: readonly string[] = [
    'Click Copy.',
    'Paste the text into a file at the top of your workspace folder: `.github/copilot-instructions.md` for GitHub Copilot, `CLAUDE.md` for Claude Code, or `AGENTS.md` for ChatGPT (Codex) and most other agents. If the file already exists, add the text at the end. The agent reads it at the start of every chat.',
    'Or paste the text into a chat before your request.',
    'Agents that can call XLIDE\'s tools, such as GitHub Copilot, work on the file through them.',
    'Agents that work on files on disk, such as Claude and ChatGPT, cannot reach a module on their own. XLIDE\'s author recommends installing Python and his pyOpenVBA, pyvbaanalysis and pyvbaharness libraries, which read, check and run the VBA in the file itself. The agent asks you first, and without them falls back to export and import.',
    'A VB6 project\'s modules are ordinary files, so any agent edits those directly.',
];

/** The instructions, as Markdown. */
export const AGENT_INSTRUCTIONS: string = [
    '# XLIDE Agent Instructions',
    '',
    'This workspace uses XLIDE, a VS Code extension for the VBA in macro-enabled Office files and for Visual Basic 6 projects. XLIDE reads and writes the VBA project inside a file directly. Office is needed only to run macros and tests.',
    '',
    'Files it handles: Excel (.xlsm, .xlsb, .xlam, .xltm, .xls, .xlt, .xla), Word (.docm, .dotm, .doc, .dot), PowerPoint (.pptm, .potm, .ppsm, .ppam, .ppt, .ppa), Access (.accdb, .accda, .mdb, .mda), and VB6 projects (.vbp).',
    '',
    '## Rules for every agent',
    '',
    '- The VBA lives inside the Office file, and the file is the only source of truth for it. Exported .bas, .cls and .frm files are copies and can be stale.',
    '- Change an Office file only through XLIDE or pyOpenVBA, the library described below. Do not unzip, rezip, hex-edit or hand-script it, and do not touch vbaProject.bin. Such an edit can corrupt the file or silently drop its code.',
    '- Do not drive Office with COM, PowerShell or VBScript automation of your own, and never open, close or kill an Office application the user is running. On Windows, pyvbaharness runs VBA in an instance it owns.',
    '- Install nothing without asking. If a task needs Python or a package, tell the user which one, what it is for, and the exact command, then wait for their answer.',
    '- Read the code you are about to change, and change only what the task needs.',
    '- Keep VBA source and cell values ASCII unless the user asks otherwise.',
    '- Ask the user before anything hard to undo: deleting a module or a shape, overwriting cells that hold data, or writing to a project that is digitally signed (the write removes the signature) or password-protected.',
    '- Verify every change as described below, and report only what you observed.',
    '',
    '## Which way to work',
    '',
    '- If you can call tools named xlide_*, work through them. GitHub Copilot Chat can in Agent mode, with any model it offers, and so can other agents that VS Code gives its language model tools. See "With XLIDE\'s tools".',
    '- If you cannot, reach a module with pyOpenVBA, as a VS Code document, or through an export. See "Without XLIDE\'s tools".',
    '- A UserForm\'s controls and layout are edited as XML either way. See "UserForms".',
    '- A VB6 project keeps each module in its own text file. See "VB6 projects".',
    '',
    '## With XLIDE\'s tools',
    '',
    'Workflow:',
    '',
    '1. Find the file with xlide_listProjects when the user has not named one. Pass absolute paths to every tool.',
    '2. Call xlide_getProjectInfo once per file. It lists the modules and, for Excel, the sheets and named ranges, and says whether the project is signed or password-protected.',
    '3. Read with xlide_readModule. Its first line is a contentToken: pass it back as expectedContentToken to xlide_writeModule, so the write is refused if the module changed after your read.',
    '4. Write with xlide_writeModule. It replaces the module\'s code, so send all of it; header lines you include are replaced by the module\'s own. It creates a missing module: a standard module, or a class module with kind "class".',
    '5. After every VBA change, call xlide_analyzeProject. Treat any problem as a build failure: fix it and analyze again until problems is empty.',
    '6. If the file has @xlide-test tests and the change touches tested code, run xlide_runVbaTests. It needs Windows, the file\'s Office application, and the XlideAssert module, which the user installs from Unit Tests in the XLIDE sidebar.',
    '7. Before a commit, call xlide_gitChanges to see what changed inside the file since HEAD, one diff per module. git diff cannot show this: the file is binary.',
    '',
    'Tools that only read:',
    '',
    '- xlide_listProjects: the macro-enabled files and VB6 projects in the workspace.',
    '- xlide_getProjectInfo: modules, sheets and named ranges in one call.',
    '- xlide_validateProject: structural problems in the project, before risky work.',
    '- xlide_listModules: module names and kinds.',
    '- xlide_listSubs: the procedures in one module.',
    '- xlide_readModule: a module\'s code.',
    '- xlide_searchModules: where a name is declared or used, across every module.',
    '- xlide_analyzeProject: XLIDE\'s analyzer over the whole project.',
    '- xlide_gitChanges: each module\'s diff against a git revision.',
    '- xlide_listSheets: sheet names and used ranges.',
    '- xlide_readCells: cell values, as Excel last calculated them.',
    '- xlide_readFormulas: cell formulas.',
    '- xlide_listShapes: shapes, buttons and form controls, with the Sub each one runs.',
    '',
    'Tools that change something (the user confirms each call):',
    '',
    '- xlide_writeModule: create a module or replace its code.',
    '- xlide_renameModule: rename a module.',
    '- xlide_deleteModule: delete a module.',
    '- xlide_createProject: create a new macro-enabled file. It never overwrites one.',
    '- xlide_writeCells: write values and formulas into cells.',
    '- xlide_editShape: add, move, relabel or delete a shape or button, or link it to a Sub.',
    '- xlide_runVbaTests: run the tests in the file\'s Office application. Results go to tests/ beside the file by default.',
    '- xlide_exportModules: export modules to a folder. Only when the user asks.',
    '- xlide_configureExportMode: set how exports treat stale files. Only when the user asks.',
    '',
    'Rules for the tools:',
    '',
    '- Change VBA only through xlide_writeModule, even in a module the user has open. XLIDE shows the user a before/after diff of each write and marks the module for Review, Keep or Revert. An edit made in an open xlide-vba: editor skips that review. If the user reverts, read the module again before your next edit.',
    '- Do not work from exported .bas or .cls files unless the user asks about them.',
    '- Module names must be valid VBA identifiers. Sheet and workbook modules (Sheet1, ThisWorkbook, ThisDocument) can be written but not renamed or deleted. A UserForm\'s module holds only its code; see "UserForms" for its controls.',
    '- If a write fails because the file is open in its Office application, tell the user. Depending on the user\'s settings, XLIDE closes and reopens the file itself; never do that yourself.',
    '- Access runs its compiled project, so a write takes effect when Access next opens the database.',
    '- xlide_readCells returns results as Excel last calculated them. A formula you write, and any formula that depends on a cell you write, keeps its old result until the workbook is next opened in Excel. Do not report a result Excel has not calculated.',
    '- Write formulas as you would type them into Excel 365, such as =XLOOKUP(...) or =FILTER(...), with no _xlfn. prefixes. If Excel would reject any formula, nothing is written and the error names the cell; fix it and write again.',
    '- A shape\'s macro must be a Public Sub with no required parameters that is already in the project, so write the Sub first. Name it as Proc, or Module.Proc when two modules have one. ActiveX controls are listed but not edited: their code is event procedures in the sheet\'s module.',
    '',
    'GitHub Copilot:',
    '',
    '- XLIDE\'s tools run in Agent mode. If they are missing, ask the user to switch to Agent mode and enable XLIDE in the chat\'s tool picker.',
    '- The user can point you at a tool with #, such as #xlideReadModule.',
    '- A declined confirmation is the user\'s answer. Do not repeat the call unchanged.',
    '- Your own file tools cannot change the VBA inside an Office file. Use XLIDE\'s tools for it.',
    '',
    '## Without XLIDE\'s tools',
    '',
    'A module inside an Office file has no path on disk. XLIDE serves each one to VS Code as a document at an xlide-vba: address, such as xlide-vba:/C:/Work/Budget.xlsm/Module1.bas, and the matching disk path, C:/Work/Budget.xlsm/Module1.bas, does not exist: a tool that opens, reads or writes files by path gets "no such file or directory". A list of open editors does show such a tab, so seeing a module open is not the same as being able to read it.',
    '',
    'Three ways in, best first:',
    '',
    '- Python, once the user agrees to it. For an agent that is not GitHub Copilot, the author of XLIDE recommends installing Python and three libraries of his: pyOpenVBA to read and write the VBA inside a file, pyvbaanalysis to check it, and pyvbaharness to run it. They work on the file itself, with no export step. See "The Python libraries".',
    '- If your edits go through VS Code\'s editor APIs rather than the file system, edit that document and save it. Saving writes the module into the Office file. XLIDE cannot tell such an edit from the user\'s typing, so it shows no before/after review: tell the user which modules you changed. If a save stops at VS Code\'s prompt that the file is newer, the module changed outside the editor, for example in the VBE; tell the user rather than overwriting it.',
    '- Otherwise, work on exported module files, and let the user carry them in and out:',
    '  1. Ask the user to export: in the XLIDE view of the Explorer, right-click the file and choose Export All Modules to Folder (or run "XLIDE: Export All Modules to Folder"), then apply the preview. Ask which folder they chose. A folder saved in the preview is also recorded as exportFolder in the settings file beside the Office file: Budget.xlsm.xlide_settings.json for Budget.xlsm.',
    '  2. Edit the exported files. The file name is the module name. A .bas file is a standard module; a .cls file is a class, a sheet or workbook module, or a form\'s code. Keep the header lines at the top of each exported file as they are. A new file can be code only: a new .bas becomes a standard module and a new .cls a class module.',
    '  3. Do not create files for sheets, the workbook or forms: import cannot create those modules.',
    '  4. Ask the user to import: right-click the file and choose Import Modules from Folder (or run "XLIDE: Import Modules from Folder"). XLIDE shows the change to every module before it writes anything, and the user applies it. Access databases can be exported but not imported.',
    '',
    'Either way:',
    '',
    '- Never report a module as changed because you wrote an exported .bas or .cls. Those files are copies, and nothing reads them back into the Office file until the user imports them.',
    '- To add, rename or delete a module, ask the user to right-click in the XLIDE view and choose Add Standard Module, Add Class Module, Rename Module or Delete Module. An import can also create a standard or class module from a new file.',
    '- Check your work. With pyvbaanalysis, run it yourself. Otherwise ask the user to run Analyze Project and give you the report: Copy JSON puts it on the clipboard, and Export JSON saves it to a file you can read, by default Budget.xlsm.xlide-analysis.json beside Budget.xlsm. XLIDE also reports an open module\'s findings in VS Code\'s Problems panel, if you can read them there. Treat any problem as a build failure.',
    '- If the file has tests, run them with pyvbaharness, or ask the user to run them from Unit Tests in the XLIDE sidebar. XLIDE writes the results to tests/status_for_ci.json beside the file by default, with each run\'s details in its own folder under tests/.',
    '- You cannot read or change worksheet cells or shapes. Describe the change for the user, or suggest making it with GitHub Copilot, which can.',
    '',
    'The rules above about module names, sheet and workbook modules, and ASCII apply to both ways.',
    '',
    '## The Python libraries',
    '',
    'Three libraries by the author of XLIDE, and the route he recommends for an agent that cannot call XLIDE\'s tools. Install nothing before the user agrees: say which package, what it is for, and the command, then wait.',
    '',
    '### pyOpenVBA: read and write the VBA in a file',
    '',
    'Pure Python, no dependencies, no Office, any platform. It reads and writes the VBA in Excel (.xlsm, .xlsb, .xlam, .xls), Word (.docm, .dotm, .doc), PowerPoint (.pptm, .potm, .ppt) and Access (.accdb, .mdb), and the file reopens in its application without a repair prompt. It also reads and writes UserForm designs and Excel Power Query.',
    '',
    '```',
    'pip install pyOpenVBA',
    '```',
    '',
    '```python',
    'from pyopenvba import ExcelFile',
    '',
    'with ExcelFile("Budget.xlsm") as wb:',
    '    print(wb.module_names())          # [\'ThisWorkbook\', \'Sheet1\', \'Module1\']',
    '    source = wb.get_module("Module1")',
    '    wb.set_module("Module1", source.replace("MsgBox", "Debug.Print"))',
    '    wb.save()                         # in place; wb.save("copy.xlsm") for a copy',
    '```',
    '',
    'WordFile, PowerPointFile and AccessDatabase have the same four calls: module_names(), get_module(), set_module(), save(). wb.vba_project() gives add_module(name, source, kind=...), rename_module(old, new) and delete_module(name). ExcelFile.create_new("new.xlsm") makes a file from a template Office authored, and the CLI moves whole folders: `python -m pyopenvba ls Budget.xlsm`, `pull Budget.xlsm ./vba`, `push ./vba Budget.xlsm`.',
    '',
    'Two guards, and both mean stop and ask the user: a save refuses a password-protected project unless you pass allow_protected=True, and a save that invalidates a digital signature drops the signature and warns. Do not write while the file is open in its Office application. XLIDE notices your write and reloads any module the user has open.',
    '',
    '### pyvbaanalysis: check the VBA',
    '',
    'Static analysis for VBA, without Office and without running anything. More than a hundred checks: type errors, undeclared variables, calls to procedures or members that do not exist, what the VBA compiler would reject (including a Declare without PtrSafe on 64-bit Office), and likely run-time failures. Each file is measured against its own host\'s object model, and it reports a problem only when it can prove one.',
    '',
    '```',
    'pip install pyvbaanalysis',
    'pyvbaanalysis Budget.xlsm                  # exits 1 when it finds problems',
    'pyvbaanalysis ./exported_modules --format json',
    '```',
    '',
    '```python',
    'from pyvbaanalysis import analyze_office_file',
    '',
    'for module, problems in analyze_office_file("Budget.xlsm").items():',
    '    for problem in problems:',
    '        print(module, problem.severity.value, problem.code, problem.message)',
    '```',
    '',
    'analyze_module(source) checks one module\'s text, and analyze_loose_files([...]) checks exported files together so references between them resolve. Run it after every change you make, and treat any problem as a build failure.',
    '',
    '### pyvbaharness: run the VBA',
    '',
    'Runs macros and tests in desktop Excel, Word, PowerPoint and Access. Windows only, and it needs the application installed; pip brings pywin32 with it. It starts an instance it owns, never attaches to one the user is running, holds a deadline over every call, and traps VBA errors as data instead of leaving a modal dialog open.',
    '',
    '```',
    'pip install pyvbaharness',
    'pyvbaharness doctor                        # what is installed, what is missing',
    'pyvbaharness run Budget.xlsm --proc Model.Recalculate',
    'pyvbaharness check Budget.xlsm             # compile check only',
    '```',
    '',
    '```python',
    'from pyvbaharness import ExcelSession',
    '',
    'with ExcelSession() as excel:',
    '    excel.open_workbook(r"C:\\Work\\Budget.xlsm", read_only=True)',
    '    result = excel.run_macro("Module1.Recalculate", timeout=120)',
    '    print(result.outcome, result.value)    # \'passed\', the return value',
    '```',
    '',
    'A document opens read-only and closes without saving unless you call save_as, which takes macro-enabled formats only. run_vba(source, proc=...) injects source and calls one procedure from it, and run_tests(source) runs every zero-argument Test* procedure and reports each one. WordSession, PowerPointSession and AccessSession drive the other hosts with the same calls. Excel, Word and PowerPoint need "Trust access to the VBA project object model" turned on in the Trust Center; tell the user rather than changing that setting for them. PowerPoint cannot run hidden and refuses to start while the user has PowerPoint open.',
    '',
    '## UserForms',
    '',
    'A UserForm\'s code is its module. Its controls and layout are in its form markup, an XML document at an xlide-vba: address ending in .form, which the user opens with Open Form Markup on the form in the XLIDE view. Edit the markup and save it to change the form. If any of it does not parse, nothing is applied. Like a module, it is a document in VS Code and not a file on disk, and no XLIDE tool reads or writes it.',
    '',
    '## VB6 projects',
    '',
    '- A .vbp project\'s modules are the .bas, .cls, .frm, .ctl and .pag files it lists, and XLIDE edits those files in place. With XLIDE\'s tools, read and write them through the tools; without, edit the files directly.',
    '- Keep each file\'s header: the VERSION line, a form\'s Begin ... End block, and the Attribute lines. Never edit a .frx file; it is binary.',
    '- To rename, add or remove a module, change its file and its line in the .vbp together, writing the line the way the existing ones are written.',
    '',
    '## When you finish',
    '',
    'Report what changed (modules, cells, shapes), how you verified it and with what result, and what the user still has to do: review a diff, import the files, or open the workbook in Excel so its formulas recalculate.',
    '',
].join('\n');
