export const XLIDE_ASSERT_MODULE_NAME = 'XlideAssert';

export const XLIDE_ASSERT_MODULE_SOURCE = [
    'Attribute VB_Name = "XlideAssert"',
    'Option Explicit',
    '',
    'Private Const XLIDE_ASSERTION_ERROR As Long = vbObjectError + 513',
    '',
    'Public Sub AreEqual(ByVal expected As Variant, ByVal actual As Variant, Optional ByVal message As String = "")',
    '    If Not ValuesEqual(expected, actual) Then',
    '        Fail BuildMessage(message, "Expected <" & ValueText(expected) & "> but was <" & ValueText(actual) & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub AreNotEqual(ByVal expected As Variant, ByVal actual As Variant, Optional ByVal message As String = "")',
    '    If ValuesEqual(expected, actual) Then',
    '        Fail BuildMessage(message, "Did not expect <" & ValueText(actual) & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsTrue(ByVal condition As Boolean, Optional ByVal message As String = "")',
    '    If Not condition Then',
    '        Fail BuildMessage(message, "Expected True but was False.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsFalse(ByVal condition As Boolean, Optional ByVal message As String = "")',
    '    If condition Then',
    '        Fail BuildMessage(message, "Expected False but was True.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub AreSame(ByVal expected As Object, ByVal actual As Object, Optional ByVal message As String = "")',
    '    If Not expected Is actual Then',
    '        Fail BuildMessage(message, "Expected both object references to point to the same instance.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsNothing(ByVal actual As Object, Optional ByVal message As String = "")',
    '    If Not actual Is Nothing Then',
    '        Fail BuildMessage(message, "Expected Nothing but received an object reference.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsNotNothing(ByVal actual As Object, Optional ByVal message As String = "")',
    '    If actual Is Nothing Then',
    '        Fail BuildMessage(message, "Expected an object reference but received Nothing.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub Fail(Optional ByVal message As String = "Assertion failed.")',
    '    Err.Raise XLIDE_ASSERTION_ERROR, "XLIDE.Assert", message',
    'End Sub',
    '',
    'Public Sub Throws(ByVal expectedErrorNumber As Long, ByVal macroName As String, Optional ByVal message As String = "")',
    '    On Error GoTo Caught',
    '    Application.Run macroName',
    '    On Error GoTo 0',
    '    Fail BuildMessage(message, "Expected error " & CStr(expectedErrorNumber) & " but no error was raised.")',
    '    Exit Sub',
    'Caught:',
    '    Dim actualNumber As Long',
    '    Dim actualDescription As String',
    '    actualNumber = Err.Number',
    '    actualDescription = Err.Description',
    '    On Error GoTo 0',
    '    If actualNumber <> expectedErrorNumber Then',
    '        Fail BuildMessage(message, "Expected error " & CStr(expectedErrorNumber) & " but got " & CStr(actualNumber) & ": " & actualDescription)',
    '    End If',
    'End Sub',
    '',
    'Public Sub DoesNotThrow(ByVal macroName As String, Optional ByVal message As String = "")',
    '    On Error GoTo Caught',
    '    Application.Run macroName',
    '    On Error GoTo 0',
    '    Exit Sub',
    'Caught:',
    '    Dim actualNumber As Long',
    '    Dim actualDescription As String',
    '    actualNumber = Err.Number',
    '    actualDescription = Err.Description',
    '    On Error GoTo 0',
    '    Fail BuildMessage(message, "Expected no error but got " & CStr(actualNumber) & ": " & actualDescription)',
    'End Sub',
    '',
    'Public Function AssertionErrorNumber() As Long',
    '    AssertionErrorNumber = XLIDE_ASSERTION_ERROR',
    'End Function',
    '',
    'Private Function ValuesEqual(ByVal expected As Variant, ByVal actual As Variant) As Boolean',
    '    On Error GoTo NotEqual',
    '    If IsObject(expected) Or IsObject(actual) Then',
    '        ValuesEqual = False',
    '    ElseIf IsArray(expected) Or IsArray(actual) Then',
    '        ValuesEqual = False',
    '    ElseIf IsNull(expected) Or IsNull(actual) Then',
    '        ValuesEqual = IsNull(expected) And IsNull(actual)',
    '    ElseIf IsEmpty(expected) Or IsEmpty(actual) Then',
    '        ValuesEqual = IsEmpty(expected) And IsEmpty(actual)',
    '    Else',
    '        ValuesEqual = (expected = actual)',
    '    End If',
    '    Exit Function',
    'NotEqual:',
    '    ValuesEqual = False',
    'End Function',
    '',
    'Private Function ValueText(ByVal value As Variant) As String',
    '    On Error GoTo Fallback',
    '    If IsObject(value) Then',
    '        ValueText = "Object(" & TypeName(value) & ")"',
    '    ElseIf IsArray(value) Then',
    '        ValueText = "Array(" & TypeName(value) & ")"',
    '    ElseIf IsNull(value) Then',
    '        ValueText = "Null"',
    '    ElseIf IsEmpty(value) Then',
    '        ValueText = "Empty"',
    '    Else',
    '        ValueText = CStr(value)',
    '    End If',
    '    Exit Function',
    'Fallback:',
    '    ValueText = TypeName(value)',
    'End Function',
    '',
    'Private Function BuildMessage(ByVal userMessage As String, ByVal defaultMessage As String) As String',
    '    If Len(Trim$(userMessage)) > 0 Then',
    '        BuildMessage = userMessage & " " & defaultMessage',
    '    Else',
    '        BuildMessage = defaultMessage',
    '    End If',
    'End Function',
    '',
].join('\r\n');

export function normalizeVbaTestSupportModuleSource(source: string): string {
    return source
        .replace(/\r\n|\r/g, '\n')
        .split('\n')
        .filter((line) => !/^\s*Attribute\s+VB_/i.test(line))
        .join('\n')
        .trim();
}
