import { isVbaAttributeLine, normalizeEol } from './vbaStructuralAnalysis';

export const XLIDE_ASSERT_MODULE_NAME = 'XlideAssert';

/**
 * JSON string-escaping helper shared by every generated VBA module that emits
 * result JSON (XlideAssert and the direct test runner), so the escaping logic
 * exists once.
 */
export const XLIDE_VBA_JSON_ESCAPE_FUNCTION_LINES = [
    'Private Function JsonEscape(ByVal value As String) As String',
    '    Dim escaped As String',
    '    escaped = Replace(value, Chr$(92), Chr$(92) & Chr$(92))',
    '    escaped = Replace(escaped, Chr$(34), Chr$(92) & Chr$(34))',
    '    escaped = Replace(escaped, vbCrLf, Chr$(92) & "n")',
    '    escaped = Replace(escaped, vbCr, Chr$(92) & "n")',
    '    escaped = Replace(escaped, vbLf, Chr$(92) & "n")',
    '    JsonEscape = escaped',
    'End Function',
] as const;

export const XLIDE_ASSERT_MODULE_SOURCE = [
    'Attribute VB_Name = "XlideAssert"',
    'Option Explicit',
    '',
    'Private Const XLIDE_ASSERTION_ERROR As Long = vbObjectError + 513',
    'Private mLastFailureMessage As String',
    'Private mOutputJsonItems As String',
    '',
    'Public Sub AreEqual(ByVal expected As Variant, ByVal actual As Variant, Optional ByVal message As String = "")',
    '    If Not ValuesEqual(expected, actual) Then',
    '        Fail BuildMessage(message, "Expected <" & ValueText(expected) & "> but was <" & ValueText(actual) & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub AreNotEqual(ByVal expected As Variant, ByVal actual As Variant, Optional ByVal message As String = "")',
    '    If ValuesEqual(expected, actual) Then',
    '        Fail BuildMessage(message, "Did not expect <" & ValueText(actual) & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsTrue(ByVal condition As Boolean, Optional ByVal message As String = "")',
    '    If Not condition Then',
    '        Fail BuildMessage(message, "Expected True but was False.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsFalse(ByVal condition As Boolean, Optional ByVal message As String = "")',
    '    If condition Then',
    '        Fail BuildMessage(message, "Expected False but was True.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub AreSame(ByVal expected As Object, ByVal actual As Object, Optional ByVal message As String = "")',
    '    If Not expected Is actual Then',
    '        Fail BuildMessage(message, "Expected both object references to point to the same instance.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub AreNotSame(ByVal expected As Object, ByVal actual As Object, Optional ByVal message As String = "")',
    '    If expected Is actual Then',
    '        Fail BuildMessage(message, "Did not expect both object references to point to the same instance.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsNothing(ByVal actual As Object, Optional ByVal message As String = "")',
    '    If Not actual Is Nothing Then',
    '        Fail BuildMessage(message, "Expected Nothing but received an object reference.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsNotNothing(ByVal actual As Object, Optional ByVal message As String = "")',
    '    If actual Is Nothing Then',
    '        Fail BuildMessage(message, "Expected an object reference but received Nothing.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsNullValue(ByVal actual As Variant, Optional ByVal message As String = "")',
    '    If Not IsNull(actual) Then',
    '        Fail BuildMessage(message, "Expected Null but was <" & ValueText(actual) & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsNotNullValue(ByVal actual As Variant, Optional ByVal message As String = "")',
    '    If IsNull(actual) Then',
    '        Fail BuildMessage(message, "Expected a non-Null value.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsEmptyValue(ByVal actual As Variant, Optional ByVal message As String = "")',
    '    If Not IsEmpty(actual) Then',
    '        Fail BuildMessage(message, "Expected Empty but was <" & ValueText(actual) & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsNotEmptyValue(ByVal actual As Variant, Optional ByVal message As String = "")',
    '    If IsEmpty(actual) Then',
    '        Fail BuildMessage(message, "Expected a non-Empty value.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub Contains(ByVal actual As Variant, ByVal expectedSubstring As Variant, Optional ByVal message As String = "")',
    '    Dim actualText As String',
    '    Dim expectedText As String',
    '    If Not TryString(actual, actualText) Or Not TryString(expectedSubstring, expectedText) Then',
    '        Fail BuildMessage(message, "Expected a text value containing <" & ValueText(expectedSubstring) & "> but was <" & ValueText(actual) & ">.")',
    '    ElseIf InStr(1, actualText, expectedText, vbBinaryCompare) = 0 Then',
    '        Fail BuildMessage(message, "Expected <" & actualText & "> to contain <" & expectedText & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub DoesNotContain(ByVal actual As Variant, ByVal unexpectedSubstring As Variant, Optional ByVal message As String = "")',
    '    Dim actualText As String',
    '    Dim unexpectedText As String',
    '    If Not TryString(actual, actualText) Or Not TryString(unexpectedSubstring, unexpectedText) Then',
    '        Fail BuildMessage(message, "Expected a text value that does not contain <" & ValueText(unexpectedSubstring) & "> but was <" & ValueText(actual) & ">.")',
    '    ElseIf InStr(1, actualText, unexpectedText, vbBinaryCompare) > 0 Then',
    '        Fail BuildMessage(message, "Did not expect <" & actualText & "> to contain <" & unexpectedText & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub StartsWith(ByVal actual As Variant, ByVal expectedPrefix As Variant, Optional ByVal message As String = "")',
    '    Dim actualText As String',
    '    Dim prefixText As String',
    '    If Not TryString(actual, actualText) Or Not TryString(expectedPrefix, prefixText) Then',
    '        Fail BuildMessage(message, "Expected a text value starting with <" & ValueText(expectedPrefix) & "> but was <" & ValueText(actual) & ">.")',
    '    ElseIf Left$(actualText, Len(prefixText)) <> prefixText Then',
    '        Fail BuildMessage(message, "Expected <" & actualText & "> to start with <" & prefixText & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub EndsWith(ByVal actual As Variant, ByVal expectedSuffix As Variant, Optional ByVal message As String = "")',
    '    Dim actualText As String',
    '    Dim suffixText As String',
    '    If Not TryString(actual, actualText) Or Not TryString(expectedSuffix, suffixText) Then',
    '        Fail BuildMessage(message, "Expected a text value ending with <" & ValueText(expectedSuffix) & "> but was <" & ValueText(actual) & ">.")',
    '    ElseIf Right$(actualText, Len(suffixText)) <> suffixText Then',
    '        Fail BuildMessage(message, "Expected <" & actualText & "> to end with <" & suffixText & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub Fail(Optional ByVal message As String = "Assertion failed.")',
    '    If Len(mLastFailureMessage) = 0 Then',
    '        mLastFailureMessage = message',
    '    End If',
    'End Sub',
    '',
    'Public Sub WriteLine(ByVal message As Variant)',
    '    If Len(mOutputJsonItems) > 0 Then',
    '        mOutputJsonItems = mOutputJsonItems & ","',
    '    End If',
    '    mOutputJsonItems = mOutputJsonItems & Chr$(34) & JsonEscape(ValueText(message)) & Chr$(34)',
    'End Sub',
    '',
    'Public Sub ResetLastFailure()',
    '    mLastFailureMessage = ""',
    'End Sub',
    '',
    'Public Sub ResetOutput()',
    '    mOutputJsonItems = ""',
    'End Sub',
    '',
    'Public Sub ResetTestState()',
    '    ResetLastFailure',
    '    ResetOutput',
    'End Sub',
    '',
    'Public Function LastFailureMessage() As String',
    '    LastFailureMessage = mLastFailureMessage',
    'End Function',
    '',
    'Public Function OutputJson() As String',
    '    OutputJson = "[" & mOutputJsonItems & "]"',
    'End Function',
    '',
    'Public Sub Throws(ByVal expectedErrorNumber As Long, ByVal macroName As String, Optional ByVal message As String = "")',
    '    On Error GoTo Caught',
    '    Application.Run macroName',
    '    On Error GoTo 0',
    '    Fail BuildMessage(message, "Expected error " & CStr(expectedErrorNumber) & " but no error was raised.")',
    '    Exit Sub',
    'Caught:',
    '    Dim actualNumber As Long',
    '    Dim actualDescription As String',
    '    actualNumber = Err.Number',
    '    actualDescription = Err.Description',
    '    On Error GoTo 0',
    '    If actualNumber <> expectedErrorNumber Then',
    '        Fail BuildMessage(message, "Expected error " & CStr(expectedErrorNumber) & " but got " & CStr(actualNumber) & ": " & actualDescription)',
    '    End If',
    'End Sub',
    '',
    'Public Sub DoesNotThrow(ByVal macroName As String, Optional ByVal message As String = "")',
    '    On Error GoTo Caught',
    '    Application.Run macroName',
    '    On Error GoTo 0',
    '    Exit Sub',
    'Caught:',
    '    Dim actualNumber As Long',
    '    Dim actualDescription As String',
    '    actualNumber = Err.Number',
    '    actualDescription = Err.Description',
    '    On Error GoTo 0',
    '    Fail BuildMessage(message, "Expected no error but got " & CStr(actualNumber) & ": " & actualDescription)',
    'End Sub',
    '',
    'Public Function AssertionErrorNumber() As Long',
    '    AssertionErrorNumber = XLIDE_ASSERTION_ERROR',
    'End Function',
    '',
    'Private Function ValuesEqual(ByVal expected As Variant, ByVal actual As Variant) As Boolean',
    '    On Error GoTo NotEqual',
    '    If IsObject(expected) Or IsObject(actual) Then',
    '        ValuesEqual = False',
    '    ElseIf IsArray(expected) Or IsArray(actual) Then',
    '        ValuesEqual = False',
    '    ElseIf IsNull(expected) Or IsNull(actual) Then',
    '        ValuesEqual = IsNull(expected) And IsNull(actual)',
    '    ElseIf IsEmpty(expected) Or IsEmpty(actual) Then',
    '        ValuesEqual = IsEmpty(expected) And IsEmpty(actual)',
    '    Else',
    '        ValuesEqual = (expected = actual)',
    '    End If',
    '    Exit Function',
    'NotEqual:',
    '    ValuesEqual = False',
    'End Function',
    '',
    'Private Function ValueText(ByVal value As Variant) As String',
    '    On Error GoTo Fallback',
    '    If IsObject(value) Then',
    '        ValueText = "Object(" & TypeName(value) & ")"',
    '    ElseIf IsArray(value) Then',
    '        ValueText = "Array(" & TypeName(value) & ")"',
    '    ElseIf IsNull(value) Then',
    '        ValueText = "Null"',
    '    ElseIf IsEmpty(value) Then',
    '        ValueText = "Empty"',
    '    Else',
    '        ValueText = CStr(value)',
    '    End If',
    '    Exit Function',
    'Fallback:',
    '    ValueText = TypeName(value)',
    'End Function',
    '',
    'Private Function TryString(ByVal value As Variant, ByRef output As String) As Boolean',
    '    On Error GoTo Failed',
    '    If IsObject(value) Or IsArray(value) Or IsNull(value) Then',
    '        GoTo Failed',
    '    End If',
    '    output = CStr(value)',
    '    TryString = True',
    '    Exit Function',
    'Failed:',
    '    output = ValueText(value)',
    '    TryString = False',
    'End Function',
    '',
    'Private Function BuildMessage(ByVal userMessage As String, ByVal defaultMessage As String) As String',
    '    If Len(Trim$(userMessage)) > 0 Then',
    '        BuildMessage = userMessage & " " & defaultMessage',
    '    Else',
    '        BuildMessage = defaultMessage',
    '    End If',
    'End Function',
    '',
    ...XLIDE_VBA_JSON_ESCAPE_FUNCTION_LINES,
    '',
].join('\r\n');

export function normalizeVbaTestSupportModuleSource(source: string): string {
    return normalizeEol(source)
        .split('\n')
        .filter((line) => !isVbaAttributeLine(line))
        .join('\n')
        .trim();
}
