import { isVbaAttributeLine, normalizeEol } from './vbaSourceScan';
import { tokenize } from './analyzer';

export const XLIDE_ASSERT_MODULE_NAME = 'XlideAssert';

// IDENTIFIER CASING IS PART OF THIS MODULE'S CONTRACT. VBA cases identifiers
// project-wide to the latest declaration it sees, so every name declared here
// that also exists in a host object model or the VBA runtime must be spelled
// the way that model spells it - `Value`, `Message`, `Number`, `Source`,
// `Condition`, `MacroName`. A lowercase parameter re-spells every `.Value` and
// `Err.Number` in the user's project the moment XlideAssert is installed, and
// XlideAssert is installed permanently (issue #38).
// tests/vbaTestModuleIdentifierCasing.test.ts enforces this mechanically.

/**
 * JSON string-escaping helper shared by every generated VBA module that emits
 * result JSON (XlideAssert and the direct test runner), so the escaping logic
 * exists once.
 */
export const XLIDE_VBA_JSON_ESCAPE_FUNCTION_LINES = [
    'Private Function JsonEscape(ByVal Value As String) As String',
    '    Dim escaped As String',
    '    escaped = Replace(Value, Chr$(92), Chr$(92) & Chr$(92))',
    '    escaped = Replace(escaped, Chr$(34), Chr$(92) & Chr$(34))',
    '    escaped = Replace(escaped, vbCrLf, Chr$(92) & "n")',
    '    escaped = Replace(escaped, vbCr, Chr$(92) & "n")',
    '    escaped = Replace(escaped, vbLf, Chr$(92) & "n")',
    '    JsonEscape = escaped',
    'End Function',
] as const;

/**
 * Revision of the bundled support module, stamped into its text as a comment.
 *
 * The version gate folds identifier case (VBA owns it), so a revision whose
 * only change is casing would otherwise read as already installed and never
 * reach the workbooks that need it - which is exactly what revision 2 is.
 * Comments are compared verbatim, so this stamp is what makes a revision
 * visible. Bump it whenever the module's text changes.
 */
export const XLIDE_ASSERT_MODULE_REVISION = 2;

export const XLIDE_ASSERT_MODULE_SOURCE = [
    'Attribute VB_Name = "XlideAssert"',
    `' XLIDE test support module, revision ${XLIDE_ASSERT_MODULE_REVISION}. Generated by XLIDE; edits are replaced on update.`,
    'Option Explicit',
    '',
    'Private Const XLIDE_ASSERTION_ERROR As Long = vbObjectError + 513',
    'Private mLastFailureMessage As String',
    'Private mOutputJsonItems As String',
    'Private mTargetErrorNumber As Long',
    'Private mTargetErrorSource As String',
    'Private mTargetErrorDescription As String',
    '',
    'Public Sub AreEqual(ByVal expected As Variant, ByVal actual As Variant, Optional ByVal Message As String = "")',
    '    If Not ValuesEqual(expected, actual) Then',
    '        Fail BuildMessage(Message, "Expected <" & ValueText(expected) & "> but was <" & ValueText(actual) & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub AreNotEqual(ByVal expected As Variant, ByVal actual As Variant, Optional ByVal Message As String = "")',
    '    If ValuesEqual(expected, actual) Then',
    '        Fail BuildMessage(Message, "Did not expect <" & ValueText(actual) & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsTrue(ByVal Condition As Boolean, Optional ByVal Message As String = "")',
    '    If Not Condition Then',
    '        Fail BuildMessage(Message, "Expected True but was False.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsFalse(ByVal Condition As Boolean, Optional ByVal Message As String = "")',
    '    If Condition Then',
    '        Fail BuildMessage(Message, "Expected False but was True.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub AreSame(ByVal expected As Object, ByVal actual As Object, Optional ByVal Message As String = "")',
    '    If Not expected Is actual Then',
    '        Fail BuildMessage(Message, "Expected both object references to point to the same instance.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub AreNotSame(ByVal expected As Object, ByVal actual As Object, Optional ByVal Message As String = "")',
    '    If expected Is actual Then',
    '        Fail BuildMessage(Message, "Did not expect both object references to point to the same instance.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsNothing(ByVal actual As Object, Optional ByVal Message As String = "")',
    '    If Not actual Is Nothing Then',
    '        Fail BuildMessage(Message, "Expected Nothing but received an object reference.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsNotNothing(ByVal actual As Object, Optional ByVal Message As String = "")',
    '    If actual Is Nothing Then',
    '        Fail BuildMessage(Message, "Expected an object reference but received Nothing.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsNullValue(ByVal actual As Variant, Optional ByVal Message As String = "")',
    '    If Not IsNull(actual) Then',
    '        Fail BuildMessage(Message, "Expected Null but was <" & ValueText(actual) & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsNotNullValue(ByVal actual As Variant, Optional ByVal Message As String = "")',
    '    If IsNull(actual) Then',
    '        Fail BuildMessage(Message, "Expected a non-Null value.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsEmptyValue(ByVal actual As Variant, Optional ByVal Message As String = "")',
    '    If Not IsEmpty(actual) Then',
    '        Fail BuildMessage(Message, "Expected Empty but was <" & ValueText(actual) & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub IsNotEmptyValue(ByVal actual As Variant, Optional ByVal Message As String = "")',
    '    If IsEmpty(actual) Then',
    '        Fail BuildMessage(Message, "Expected a non-Empty value.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub Contains(ByVal actual As Variant, ByVal expectedSubstring As Variant, Optional ByVal Message As String = "")',
    '    Dim actualText As String',
    '    Dim expectedText As String',
    '    If Not TryString(actual, actualText) Or Not TryString(expectedSubstring, expectedText) Then',
    '        Fail BuildMessage(Message, "Expected a text value containing <" & ValueText(expectedSubstring) & "> but was <" & ValueText(actual) & ">.")',
    '    ElseIf InStr(1, actualText, expectedText, vbBinaryCompare) = 0 Then',
    '        Fail BuildMessage(Message, "Expected <" & actualText & "> to contain <" & expectedText & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub DoesNotContain(ByVal actual As Variant, ByVal unexpectedSubstring As Variant, Optional ByVal Message As String = "")',
    '    Dim actualText As String',
    '    Dim unexpectedText As String',
    '    If Not TryString(actual, actualText) Or Not TryString(unexpectedSubstring, unexpectedText) Then',
    '        Fail BuildMessage(Message, "Expected a text value that does not contain <" & ValueText(unexpectedSubstring) & "> but was <" & ValueText(actual) & ">.")',
    '    ElseIf InStr(1, actualText, unexpectedText, vbBinaryCompare) > 0 Then',
    '        Fail BuildMessage(Message, "Did not expect <" & actualText & "> to contain <" & unexpectedText & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub StartsWith(ByVal actual As Variant, ByVal expectedPrefix As Variant, Optional ByVal Message As String = "")',
    '    Dim actualText As String',
    '    Dim prefixText As String',
    '    If Not TryString(actual, actualText) Or Not TryString(expectedPrefix, prefixText) Then',
    '        Fail BuildMessage(Message, "Expected a text value starting with <" & ValueText(expectedPrefix) & "> but was <" & ValueText(actual) & ">.")',
    '    ElseIf Left$(actualText, Len(prefixText)) <> prefixText Then',
    '        Fail BuildMessage(Message, "Expected <" & actualText & "> to start with <" & prefixText & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub EndsWith(ByVal actual As Variant, ByVal expectedSuffix As Variant, Optional ByVal Message As String = "")',
    '    Dim actualText As String',
    '    Dim suffixText As String',
    '    If Not TryString(actual, actualText) Or Not TryString(expectedSuffix, suffixText) Then',
    '        Fail BuildMessage(Message, "Expected a text value ending with <" & ValueText(expectedSuffix) & "> but was <" & ValueText(actual) & ">.")',
    '    ElseIf Right$(actualText, Len(suffixText)) <> suffixText Then',
    '        Fail BuildMessage(Message, "Expected <" & actualText & "> to end with <" & suffixText & ">.")',
    '    End If',
    'End Sub',
    '',
    'Public Sub Fail(Optional ByVal Message As String = "Assertion failed.")',
    '    If Len(mLastFailureMessage) = 0 Then',
    '        mLastFailureMessage = Message',
    '    End If',
    'End Sub',
    '',
    'Public Sub WriteLine(ByVal Message As Variant)',
    '    If Len(mOutputJsonItems) > 0 Then',
    '        mOutputJsonItems = mOutputJsonItems & ","',
    '    End If',
    '    mOutputJsonItems = mOutputJsonItems & Chr$(34) & JsonEscape(ValueText(Message)) & Chr$(34)',
    'End Sub',
    '',
    'Public Sub ResetLastFailure()',
    '    mLastFailureMessage = ""',
    'End Sub',
    '',
    'Public Sub ResetOutput()',
    '    mOutputJsonItems = ""',
    'End Sub',
    '',
    'Public Sub ResetTestState()',
    '    ResetLastFailure',
    '    ResetOutput',
    'End Sub',
    '',
    'Public Function LastFailureMessage() As String',
    '    LastFailureMessage = mLastFailureMessage',
    'End Function',
    '',
    'Public Function OutputJson() As String',
    '    OutputJson = "[" & mOutputJsonItems & "]"',
    'End Function',
    '',
    'Public Sub Throws(ByVal expectedErrorNumber As Long, ByVal MacroName As String, Optional ByVal Message As String = "")',
    '    Dim actualNumber As Long',
    '    Dim actualDescription As String',
    '    RunTargetMacro MacroName, actualNumber, actualDescription',
    '    If actualNumber = 0 Then',
    '        Fail BuildMessage(Message, "Expected error " & CStr(expectedErrorNumber) & " but no error was raised.")',
    '    ElseIf actualNumber <> expectedErrorNumber Then',
    '        Fail BuildMessage(Message, "Expected error " & CStr(expectedErrorNumber) & " but got " & CStr(actualNumber) & ": " & actualDescription)',
    '    End If',
    'End Sub',
    '',
    'Public Sub DoesNotThrow(ByVal MacroName As String, Optional ByVal Message As String = "")',
    '    Dim actualNumber As Long',
    '    Dim actualDescription As String',
    '    RunTargetMacro MacroName, actualNumber, actualDescription',
    '    If actualNumber <> 0 Then',
    '        Fail BuildMessage(Message, "Expected no error but got " & CStr(actualNumber) & ": " & actualDescription)',
    '    End If',
    'End Sub',
    '',
    "' Called by the staged XlideTestDispatch module after it direct-calls a",
    "' target: the outcome crosses the Run boundary as recorded state, never as",
    "' a raised error, because Word surfaces a Run-target's unhandled error as a",
    "' VBE modal instead of propagating it to the calling VBA.",
    'Public Sub RecordTargetOutcome(ByVal errorNumber As Long, ByVal errorSource As String, ByVal errorDescription As String)',
    '    mTargetErrorNumber = errorNumber',
    '    mTargetErrorSource = errorSource',
    '    mTargetErrorDescription = errorDescription',
    'End Sub',
    '',
    'Private Sub RunTargetMacro(ByVal MacroName As String, ByRef actualNumber As Long, ByRef actualDescription As String)',
    '    RecordTargetOutcome 0, "", ""',
    '    Dim dispatchMissing As Boolean',
    '    On Error Resume Next',
    '    Application.Run "XlideTestDispatch.XlideInvokeTarget", MacroName',
    '    dispatchMissing = (Err.Number <> 0)',
    '    Err.Clear',
    '    On Error GoTo 0',
    '    If Not dispatchMissing Then',
    '        actualNumber = mTargetErrorNumber',
    '        actualDescription = mTargetErrorDescription',
    '        Exit Sub',
    '    End If',
    "    ' No staged dispatcher (editing time, plain installs): the classic",
    "    ' direct Run, which hosts like Excel propagate to this handler.",
    '    On Error GoTo Caught',
    '    Application.Run MacroName',
    '    On Error GoTo 0',
    '    Exit Sub',
    'Caught:',
    '    actualNumber = Err.Number',
    '    actualDescription = Err.Description',
    'End Sub',
    '',
    'Public Function AssertionErrorNumber() As Long',
    '    AssertionErrorNumber = XLIDE_ASSERTION_ERROR',
    'End Function',
    '',
    'Private Function ValuesEqual(ByVal expected As Variant, ByVal actual As Variant) As Boolean',
    '    On Error GoTo NotEqual',
    '    If IsObject(expected) Or IsObject(actual) Then',
    '        ValuesEqual = False',
    '    ElseIf IsArray(expected) Or IsArray(actual) Then',
    '        ValuesEqual = False',
    '    ElseIf IsNull(expected) Or IsNull(actual) Then',
    '        ValuesEqual = IsNull(expected) And IsNull(actual)',
    '    ElseIf IsEmpty(expected) Or IsEmpty(actual) Then',
    '        ValuesEqual = IsEmpty(expected) And IsEmpty(actual)',
    '    Else',
    '        ValuesEqual = (expected = actual)',
    '    End If',
    '    Exit Function',
    'NotEqual:',
    '    ValuesEqual = False',
    'End Function',
    '',
    'Private Function ValueText(ByVal Value As Variant) As String',
    '    On Error GoTo Fallback',
    '    If IsObject(Value) Then',
    '        ValueText = "Object(" & TypeName(Value) & ")"',
    '    ElseIf IsArray(Value) Then',
    '        ValueText = "Array(" & TypeName(Value) & ")"',
    '    ElseIf IsNull(Value) Then',
    '        ValueText = "Null"',
    '    ElseIf IsEmpty(Value) Then',
    '        ValueText = "Empty"',
    '    Else',
    '        ValueText = CStr(Value)',
    '    End If',
    '    Exit Function',
    'Fallback:',
    '    ValueText = TypeName(Value)',
    'End Function',
    '',
    'Private Function TryString(ByVal Value As Variant, ByRef output As String) As Boolean',
    '    On Error GoTo Failed',
    '    If IsObject(Value) Or IsArray(Value) Or IsNull(Value) Then',
    '        GoTo Failed',
    '    End If',
    '    output = CStr(Value)',
    '    TryString = True',
    '    Exit Function',
    'Failed:',
    '    output = ValueText(Value)',
    '    TryString = False',
    'End Function',
    '',
    'Private Function BuildMessage(ByVal userMessage As String, ByVal defaultMessage As String) As String',
    '    If Len(Trim$(userMessage)) > 0 Then',
    '        BuildMessage = userMessage & " " & defaultMessage',
    '    Else',
    '        BuildMessage = defaultMessage',
    '    End If',
    'End Function',
    '',
    ...XLIDE_VBA_JSON_ESCAPE_FUNCTION_LINES,
    '',
].join('\r\n');

/**
 * The text two copies of the support module are compared by, for the "is the
 * installed XlideAssert the one we ship?" gate.
 *
 * Identifier CASE is folded away, because VBA owns it: a declaration anywhere
 * in the project - a user's own `Dim value` - re-cases every matching
 * identifier in every module, including this one, without changing what the
 * code means (issue #38). Comparing case-sensitively read such a module as a
 * version drift and offered to reinstall a module that was already current.
 *
 * Only identifiers fold. String literals and comments are compared verbatim,
 * because VBA never rewrites those, so a difference there is a real edit.
 */
export function normalizeVbaTestSupportModuleSource(source: string): string {
    const text = normalizeEol(source)
        .split('\n')
        .filter((line) => !isVbaAttributeLine(line))
        .join('\n')
        .trim();
    return foldIdentifierCase(text);
}

const CASE_INSENSITIVE_TOKEN_KINDS = new Set(['identifier', 'keyword', 'bracketedIdentifier']);

/** Lowercases identifier-like tokens in place, leaving all other text as written. */
function foldIdentifierCase(source: string): string {
    let out = '';
    let index = 0;
    for (const token of tokenize(source)) {
        if (!CASE_INSENSITIVE_TOKEN_KINDS.has(token.kind)) {
            continue;
        }
        out += source.slice(index, token.start) + token.rawText.toLowerCase();
        index = token.end;
    }
    return out + source.slice(index);
}
